### ISSUE TITLE
Installing kubeadm

### ISSUE THREAD

**Issue by jl-aic** [kubernetes/website#39696] opened 2023-02-27 13:24 UTC
Cannot access https://packages.cloud.google.com/apt/doc/apt-key.gpg - 500 errror

**Comment by dipesh-rawat** [comment] 2023-02-27 13:46
This seems to be a duplicate of #39685
/triage duplicate

**Comment by dipesh-rawat** [comment] 2023-02-27 13:48
@jl-aic Would you please refer https://github.com/kubernetes/website/issues/39685#issuecomment-1446077195 to see if that helps.

**Closed** 2023-02-27 13:59 UTC
Labels: triage/duplicate, needs-triage

**Comment by dims** [comment] 2023-02-27 14:32
See work around with new URL here: https://github.com/kubernetes/k8s.io/pull/4837#issuecomment-1446426585
