### ISSUE TITLE
Workloads page has no information on what a Workload is

### ISSUE THREAD

**Issue by leeyspaul** [kubernetes/website#24553] opened 2020-10-13 18:17 UTC
# Issue

When I visit the Workloads [page](https://kubernetes.io/docs/concepts/workloads/) there is no information on what a Workload is, so I Googled the concept externally. It led me to this [Rancher page](https://rancher.com/learning-paths/introduction-to-kubernetes-workloads/) on what a Workload is.

<img width="1271" alt="Screen Shot 2020-10-13 at 11 15 28 AM" src="https://user-images.githubusercontent.com/16315857/95899586-a5c52f80-0d45-11eb-8b3e-841a1ce28dd9.png">

# Suggestion

It would be useful to have a quick explanation on what a Workload is on that page. It may be obvious to some, but from someone external to the whole orchestration world, it's not so obvious.

**Comment by kbhawkey** [comment] 2020-10-13 19:23
Related to PR #23737

**Comment by sftim** [comment] 2020-10-14 13:53
Duplicate of issue #23716
/triage duplicate

**Comment by leeyspaul** [comment] 2020-10-14 18:42
Thanks all :]

**Closed** 2020-10-15 07:26 UTC
Labels: needs-triage, triage/duplicate
