### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by fishingfool** [kubernetes/website#1658] opened 2016-11-10 17:37 UTC
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
Trying to run Bootcamp module 1 and terminal session is hard to use on FireFox 45.4.  After entering initial commands, terminal session will sometimes move from right of instruction to below, and is difficult to get to move back.  Tried in full screen and non full with different widths- still same issue.  Tutorial becomes more aggravating then education
![11-10-2016 10-35-53 am](https://cloud.githubusercontent.com/assets/22109295/20187487/ab22b534-a731-11e6-82b7-66345df3230f.jpg)

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by steveperry-53** [comment] 2017-10-06 02:53
I just reproduced this bug on Firefox 56.0.

**Comment by steveperry-53** [comment] 2017-10-06 03:03
@BenHall What should be our approach to fixing this?

While we're having the discussion, can you help us understand the state of the two sites:

* [Original Bootcamp](https://kubernetesbootcamp.github.io/kubernetes-bootcamp/)
* [Kubernetes Basic at kubernetes.io](https://kubernetes.io/docs/tutorials/kubernetes-basics/)

I know you have addressed several issues. Have your fixes applied to both sites? Or have the sites gotten out of sync?

**Comment by steveperry-53** [comment] 2017-10-06 03:13
@BenHall @heckj Let me just throw out some thoughts here. Maybe we should switch over to using the [Katacoda playground](https://www.katacoda.com/courses/kubernetes/playground) for these basic tutorials. We might be able to convey the same information and provide the same easy access to a cluster. The access might even be easier that what we have now, given that the current user experience is a bit temperamental. Another advantage would be that the Kubernetes version at the playground stays up to date. Just a thought. What do you think?

**Comment by steveperry-53** [comment] 2017-10-06 03:21
The more I think about it, the more I like the idea of moving the basic tutorials to the playground.

* The tutorial text would be decoupled from the command environment. We could address issues in the text easily.
* Many of the issues we've gotten have been about the tutorial mechanism, not about the tutorial steps or the behavior of Kubernetes. In the playground, we wouldn't have these kinds of infrastructure problems.

**Comment by BenHall** [comment] 2017-10-06 11:09
Sorry, I thought we had fixed this. I couldn't reproduce it, but I've removed some of the CSS selectors that may have caused an issue. Could you please retest @steveperry-53 and let me know if it has improved the situation.

**Comment by BenHall** [comment] 2017-10-06 11:13
In terms of improving the layout. If we could reduce the size of table of contents then it would have a huge impact. On a small screen it doesn't resize, meaning the important part (Katacoda) is reduced.

![screenshot 2017-10-06 12 09 02](https://user-images.githubusercontent.com/82614/31275518-74feb1d0-aa8f-11e7-8bee-1b44b72a787c.png)

Alternatively, maybe we move to the "tablet" layout earlier on smaller screens? 

![screenshot 2017-10-06 12 09 22](https://user-images.githubusercontent.com/82614/31275552-9efc0456-aa8f-11e7-878f-6c98b26dec21.png)

**Comment by heckj** [comment] 2017-10-06 14:22
The layout and compressed nature of the content are the second largest set of bugs reported, this one included. @BenHall and I were talking about that earlier as well, trying to figure out potential solutions. While the tutorials remain “hosted” within an ifram kind of setup within the broader kubernetes.io docs, the horizontal space becomes the most critical. 

I think having a “tablet layout” much earlier would be massively beneficial here - the navigation sidebar on these embedded tutorials doesn’t provide a lot of value, but takes up a significant portion of whitespace.

**Comment by BenHall** [comment] 2017-10-06 14:40
I agree with @heckj, the tablet view works nicely and already exists. Maybe anything that isn't a desktop uses the tablet view.

We can remove the survey questionnaire at the end and replace it with a "continue to next module"

**Comment by steveperry-53** [comment] 2017-10-06 16:30
I like the idea of using tablet view. I'd say let's use it for all screens, regardless of size.

I agree we should remove the questionnaire.

@BenHall @heckj I'd still like to hear your thoughts on my proposal to move this to the Katacoda playground.

**Comment by BenHall** [comment] 2017-10-06 16:36
@steveperry-53 Moving to the playground has some advantages and means we can stay up-to-date more easily. I was going to get Minikube updated for 1.8 but still waiting on the release.

From memory, the reason why went with Minikube was because it would be closer to the next steps we want the community to take. My main concern is how we re-phase the first scenario, or do we just assume that they have access to a cluster, by that Minikube, GKE or Kubeadm?

**Comment by steveperry-53** [comment] 2017-10-06 18:57
@BenHall About re-phrasing the first scenario. I guess we would save creation of your own cluster for later. We could just start by saying that, in the playground, there is already a cluster set up for you.

Let's keep the idea of moving to the playground on the back burner. I think it's probably best to first try the tablet view. That's the smallest step, and it might very well solve these problems.

**Comment by steveperry-53** [comment] 2017-10-06 19:02
Even on a desktop computer with a fairly large monitor, I still have the interface problems described in this issue. That's why I think we should use tablet view always.

**Comment by BenHall** [comment] 2017-10-06 19:19
Awesome. Will be a prototype over the weekend and see what we think :)

Ben

**Comment by BenHall** [comment] 2018-02-16 23:45
This is now live.

/close

**Closed by BenHall** 2018-02-16 23:45 UTC
Labels: Actionable, Needs Tech Review, P1, lifecycle/rotten, team/katacoda
