### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/cron-jobs/

### ISSUE THREAD

**Issue by panditb** [kubernetes/website#19003] opened 2020-02-06 07:00 UTC
**This is a Bug Report**

    We have setup the Kuberntes cluster in our Environment we have 2 master node and 4 worker node which all installed EST Time zone
`Thu Feb  6 01:55:13 EST 2020`

Cron Job is scheduled at 12:01 daily midnight 

```
Schedule:                   1 0 * * *
Concurrency Policy:         Allow
Suspend:                    False
Starting Deadline Seconds:  <unset>
Selector:                   <unset>
Parallelism:                <unset>
Completions:                <unset>
Active Deadline Seconds:    30s

```

And Job is started on 19:01 EST Time instead of 12:01 Time , I feel this running as UTC Timezone 

```
Controlled By:            CronJob/batch-daily
Parallelism:              1
Completions:              1
Start Time:               Wed, 05 Feb 2020 19:01:01 -0500
Completed At:             Wed, 05 Feb 2020 19:01:21 -0500
Duration:                 20s
Active Deadline Seconds:  30s
Pods Statuses:            0 Running / 1 Succeeded / 0 Failed

```

**Problem:**
    The cron Job is not running on the   timezone of the master node its running on the UTC Timezone ie OS layer of your Docker image 
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

v1.13.1

**Comment by sftim** [comment] 2020-02-06 23:38
It looks like this is a duplicate of issue #18579

**Closed** 2020-04-14 00:41 UTC
