### ISSUE TITLE
The link 'Kubernetes Protobuf serialization' is broken

### ISSUE THREAD

**Issue by LeonidLiashko** [kubernetes/website#34203] opened 2022-06-09 15:15 UTC
Link [Kubernetes Protobuf serialization](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/protobuf.md) from this page (https://kubernetes.io/docs/concepts/overview/kubernetes-api/) returns 404

**Comment by NitishKumar06** [comment] 2022-06-09 15:41
It basically shows _The 'kubernetes/community' repository doesn't contain the 'contributors/design-proposals/api-machinery/protobuf.md' path in 'master'_ .  Do we have to create a new page in the given path or the chances might be that this page is lost somewhere?

**Comment by jihoon-seo** [comment] 2022-06-09 20:54
Thank you for spotting the problem.
This is a duplicate of #34165.
And there is a open PR that fixes this,
so @NitishKumar06 you don't have to work on this.

/triage duplicate
/retitle The link 'Kubernetes Protobuf serialization' is broken

**Comment by NitishKumar06** [comment] 2022-06-10 03:10
okay @jihoon-seo

**Closed** 2022-06-14 03:55 UTC
Labels: triage/duplicate, needs-triage
