### ISSUE TITLE
Documentation references --service-account-signing-key flag that doesn't exist

### ISSUE THREAD

**Issue by bryfry** [kubernetes/website#31562] opened 2022-01-30 03:39 UTC
**This is a Bug Report**

**Problem:**

Documentation for cli tool kube-apiserver [[1](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/command-line-tools-reference/kube-apiserver.md)] references `service-account-signing-key` flag which doesn't exist. The intended documentation should reference the `service-account-signing-key-file` flag.  The cli tool implementation [[2](https://github.com/kubernetes/kubernetes/blob/2e68fd2857cded9cb470e3bf22ba01bb4934c6f8/cmd/kube-apiserver/app/options/options.go#L245-L246)] also has an incorrect doc-string [[3](https://github.com/kubernetes/kubernetes/blob/63e7ee43bb5394abd6dd5010be47ebcb22ec0ef8/pkg/kubeapiserver/options/authentication.go#L316-L321)].  I'll make cross-referencing issues for both projects

**Proposed Solution:**

All references to the `--service-account-signing-key` should be updated to `--service-account-signing-key-file`

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

Kubernetes Versions: [1.11+](https://github.com/kubernetes/website/blame/bc4bc85855777ddf5adcc65b390d0b3a26bc14fb/content/en/docs/reference/command-line-tools-reference/kube-apiserver.md#L916)

Additional Information:
Issue and PR on the kubernetes/kubernetes project are:
- https://github.com/kubernetes/kubernetes/issues/107862
- https://github.com/kubernetes/kubernetes/pull/107863

**Comment by sftim** [comment] 2022-01-30 22:57
/retitle Documentation references --service-account-signing-key flag that doesn't exist

**Comment by sftim** [comment] 2022-01-30 22:58
This is now essentially a duplicate of https://github.com/kubernetes/kubernetes/issues/107862

**Closed** 2022-02-21 11:42 UTC
Labels: kind/bug, triage/accepted
