### ISSUE TITLE
Move object management to Tasks

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#14273] opened 2019-05-10 22:13 UTC
**This is a Feature Request**

**What would you like to be added**

**Why is this needed**

**Comments**

**Comment by sftim** [comment] 2019-05-11 13:42
Duplicate of  #14272

**Comment by DanyC97** [comment] 2019-05-14 09:26
@steveperry-53 i'll close this in favour of #14272 where more info was provided
/close

**Closed by DanyC97** 2019-05-14 09:26 UTC
