### ISSUE TITLE
Add Best Practices guide to contributing to Kubernetes

### ISSUE THREAD

**Issue by NitishKumar06** [kubernetes/website#35374] opened 2022-07-25 15:59 UTC
**This is a Feature Request**

Although experienced developers and new folks are contributing to the K8s project. It can be beneficial especially to all the new folks where we can include a page with the motive of "Best practices in the community" depicting what are the things that should be followed and avoided. For eg. Don't spam, Try before asking, Don't work on an issue that has already been assigned, Be patient, etc.

**Why is this needed**

This page can really be helpful to all the new folks who are looking forward to contributing to the K8s project.

Comments:

If this issue gets accepted, I'd love to work on this issue since I've written a blog on it as well.

**Comment by shannonxtreme** [comment] 2022-07-26 13:51
Hey Nitish, this already exists at https://www.kubernetes.dev/docs/guide/contributing/#best-practices

But maybe there's an opportunity to expand that page?

**Comment by NitishKumar06** [comment] 2022-07-27 04:50
@shannonxtreme Thanks for mentioning this page. Shouldn't there be more points that should be included as well? WDYT @sftim ?

**Comment by sftim** [comment] 2022-07-27 09:36
This might be a duplicate of https://github.com/kubernetes/contributor-site/issues/202, or something similar to a duplicate.

/retitle Add Best Practices guide to contributing to Kubernetes

**Comment by shurup** [comment] 2022-07-27 09:44
> Hey Nitish, this already exists at https://www.kubernetes.dev/docs/guide/contributing/#best-practices

By the way, it seems useful to me to add a direct link to this "Best practices" section (or a new one that will be created in this issue?) at the [Opening a pull request](https://kubernetes.io/docs/contribute/new-content/open-a-pr/) page. (Or it can be mentioned on the parental [Contributing new content](https://kubernetes.io/docs/contribute/new-content/) page.)

Currently, there is a "general" link to the https://www.kubernetes.dev/docs/ only, so many users following the formal _Kubernetes Documentation / Contribute_ guide might miss these important practices that might improve the quality of their first commits/PRs.

**Comment by sftim** [comment] 2022-07-27 09:50
My advice: close this issue (it's done!), and open new issues. One new issue for each specific change that would make https://k8s.dev/ pages more discoverable.

**Comment by NitishKumar06** [comment] 2022-07-28 02:37
@sftim @shurup I'd like to take some suggestions before closing this issue: 

I believe the above changes that have been mentioned are necessary to be included. Would it be a better idea if we just include more points on the following page: https://www.kubernetes.dev/docs/guide/contributing/#best-practices

**Comment by shurup** [comment] 2022-07-28 02:56
@NitishKumar06 hi! Following the @sftim recommendation, I've started creating a new issue proposing to add the "Best practices" link to the existing "Kubernetes Documentation / Contribute" guide. However, I refrained from this idea in the end. While analyzing the existing content in a more careful manner, I discovered the [Opening a pull request](https://kubernetes.io/docs/contribute/new-content/open-a-pr/) already features the main points of existing Best practices and even presents them in more detail, e.g., it explains better about writing ```fixes #123``` in the PR body, squashing commits, etc.

So, as I see it now, the existing "Best practices" at kubernetes.dev is a quick summary of what is already described in the "Opening a pull request" guide. If a new contributor carefully follows this guide, all practices should be in place.

As far as I understand, improving the existing "Best practices" at kubernetes.dev should be discussed in the [relevant repo](https://github.com/kubernetes/contributor-site). Then, if/when this list is extended, it would be reasonable to raise the question of additional linking to them (from the kubernetes.io/docs/contribute docs) again.

**Comment by NitishKumar06** [comment] 2022-07-30 05:10
@shurup I agree with your points. But don't you think we can add a few more basic points to the following page: https://www.kubernetes.dev/docs/guide/contributing/#best-practices so that whenever a newbie reads it, they get aware of the primary community practices to be followed?

The points are mentioned really well when talking about [Opening a pull request](https://kubernetes.io/docs/contribute/new-content/open-a-pr/). Still, I feel like there should be some point in knowing the basic community practices. 

Many times, folks expect their answer to be answered at the same time not knowing that this is volunteer work. Sometimes spamming happens, and sometimes issues get closed just because two people fight to work on the same issue. Sometimes people get unnecessary personal DMS with a single message saying "Hi, Hello".

Don't you think this should be at least mentioned what to avoid and what not to?

WDYT @sftim @shurup

**Comment by sftim** [comment] 2022-07-31 17:44
For discussions about changes to https://www.kubernetes.dev/docs/guide/contributing/#best-practices, open an issue against https://github.com/kubernetes/contributor-site and use that issue to hold the discussion.

_This_ repo is mainly about documenting Kubernetes for its end users.

**Closed** 2022-08-01 15:39 UTC
Labels: kind/feature, needs-triage
