### ISSUE TITLE
Mermaid diagrams broken for `Pod Topology Spread Constraints`

### ISSUE THREAD

**Issue by dzoech** [kubernetes/website#40613] opened 2023-04-11 12:09 UTC
https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#example-one-topologyspreadconstraint

```
Syntax error in graph
mermaid version 8.13.4
```

**Comment by dipesh-rawat** [comment] 2023-04-11 12:25
/retitle Mermaid diagrams broken for `Pod Topology Spread Constraints`
There is already a similar issue #31960 raised for broken Mermaid diagrams.

@dzoech Could you please tell us what browser and OS you are viewing the page on?

/triage needs-information

**Comment by dzoech** [comment] 2023-04-11 12:36
Firefox 111.0.1 (64-bit) on Windows

Sorry for opening a duplicate ✌️

**Comment by dipesh-rawat** [comment] 2023-04-11 13:53
/close
Duplicate of https://github.com/kubernetes/website/issues/31960

**Closed by dipesh-rawat** 2023-04-11 13:53 UTC
Labels: triage/duplicate, needs-triage
