### ISSUE TITLE
“Exploring Your App” tutorial instructions aren't quite right

### ISSUE THREAD

**Issue by rvernica** [kubernetes/website#37722] opened 2022-11-05 02:46 UTC
Following the instructions on creating the deployment, the resulting pod template has no `Port` mapping. It looks like this:
```
> kubectl create deployment kubernetes-bootcamp --image=gcr.io/google-samples/kubernetes-bootcamp:v1
deployment.apps/kubernetes-bootcamp created
> kubectl describe deployments
Name:                   kubernetes-bootcamp
Namespace:              default
CreationTimestamp:      Fri, 04 Nov 2022 19:20:34 -0700
Labels:                 app=kubernetes-bootcamp
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=kubernetes-bootcamp
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  app=kubernetes-bootcamp
  Containers:
   kubernetes-bootcamp:
    Image:        gcr.io/google-samples/kubernetes-bootcamp:v1
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
```
Without a port mapping, the application cannot be accessed:
```
> curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/proxy/
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "error trying to reach service: proxy error from 127.0.0.1:6443 while dialing 10.42.0.18:80, code 503: 503 Service Unavailable",
  "reason": "ServiceUnavailable",
  "code": 503
}
```
But it is running fine:
```
> kubectl exec $POD_NAME -- curl localhost:8080 
Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-d9b4bdd78-gj656 | v=1
```
Additional info:
```
> kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4+k3s1", GitCommit:"c3f830e9b9ed8a4d9d0e2aa663b4591b923a296e", GitTreeState:"clean", BuildDate:"2022-08-25T03:45:26Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
> k3d version
k3d version v5.4.6
k3s version v1.24.4-k3s1 (default)
```

**Comment by jihoon-seo** [comment] 2022-11-08 01:39
Page: https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/
/label team/katacoda

I tried to reproduce this.

In 'Step 2 of 4', if you click the first darkgray-boxed command,
(`echo -e "\n\n\n\e[92mStarting Proxy. After starting it will not output a response. Please click the first Terminal Tab\n"; kubectl proxy`)

a new terminal tab opens, but the command is not executed unless I click the command box once again.
![image](https://user-images.githubusercontent.com/46767780/200452012-7d43df94-9062-489b-b0ae-048c1ae43667.png)

If I proceed with the command not executed properly, then I can meet the error that you countered.
![image](https://user-images.githubusercontent.com/46767780/200452307-2630dda9-fcec-433b-8626-84c2a2d8447f.png)

---

On the other hand, if I click that command box once again in the terminal tab 2 and proceed in the terminal tab 1, then I can access the application.
![image](https://user-images.githubusercontent.com/46767780/200451393-455329ef-35f4-4d84-ac5c-6c3f10369b5e.png)
![image](https://user-images.githubusercontent.com/46767780/200451708-be5f2634-70d0-4f84-a8c4-53b41432b4cc.png)

---

Yes, it seems weird that:
the guide says that
> Click on the command below to automatically open a new terminal and run the `proxy`:

but actually it opens a new terminal but does not run the command.

**Comment by sftim** [comment] 2022-12-11 22:45
/retitle “Exploring Your App” tutorial instructions aren't quite right

**Comment by tengqm** [comment] 2023-02-18 11:21
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).

**Closed by tengqm** 2023-02-18 11:21 UTC
Labels: team/katacoda, kind/bug, needs-triage
