### ISSUE TITLE
[API Reference] Commented out fields get merged into the following field's docs

### ISSUE THREAD

**Issue by tallclair** [kubernetes/website#5308] opened 2017-09-05 20:37 UTC
E.g. from https://github.com/kubernetes/kubernetes/blob/8b9e8cf80a845336fd750185d88f76711d1a5e77/pkg/api/types.go#L2087:

```
	// NOT YET IMPLEMENTED. TODO: Uncomment field once it is implemented.
	// If the affinity requirements specified by this field are not met at
	// scheduling time, the pod will not be scheduled onto the node.
	// If the affinity requirements specified by this field cease to be met
	// at some point during pod execution (e.g. due to a pod label update), the
	// system will try to eventually evict the pod from its node.
	// When there are multiple elements, the lists of nodes corresponding to each
	// podAffinityTerm are intersected, i.e. all terms must be satisfied.
	// +optional
	// RequiredDuringSchedulingRequiredDuringExecution []PodAffinityTerm

	// If the affinity requirements specified by this field are not met at
	// scheduling time, the pod will not be scheduled onto the node.
	// If the affinity requirements specified by this field cease to be met
	// at some point during pod execution (e.g. due to a pod label update), the
	// system may or may not try to eventually evict the pod from its node.
	// When there are multiple elements, the lists of nodes corresponding to each
	// podAffinityTerm are intersected, i.e. all terms must be satisfied.
	// +optional
	RequiredDuringSchedulingIgnoredDuringExecution []PodAffinityTerm
```

Becomes:

![image](https://user-images.githubusercontent.com/29742491/30082340-5068acee-923f-11e7-9ed1-a0fa68254b57.png)

Which makes it look like the `RequiredDuringSchedulingIgnoredDuringExecution` field is not yet implemented.

**Comment by tengqm** [comment] 2018-01-09 04:51
/remove-lifecycle stale

This is bad... need a fix.

**Comment by nikhita** [comment] 2018-04-09 07:10
/remove-lifecycle stale

Still needs fixing.

**Comment by tengqm** [comment] 2018-04-09 08:01
@nikhita Yes, that is true. The problem is ... whatever docs related fixes when proposed to the upstream are mostly ignored. I have tried fix similar issues upstream, but the reviews and approvals may take months if you are lucky.

**Comment by nikhita** [comment] 2018-04-09 08:50
> @nikhita Yes, that is true. The problem is ... whatever docs related fixes when proposed to the upstream are mostly ignored. I have tried fix similar issues upstream, but the reviews and approvals may take months if you are lucky.

Really sorry to hear about your experience. I believe the general suggestion (from contribex) is to ping the suggested reviewers on slack if you can't get their attention on the PR or if they are slower to respond. That should probably help getting the PRs reviewed and merged faster...

**Closed** 2018-09-06 10:41 UTC
Labels: Actionable, P2, lifecycle/rotten
