### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/ step2/3

### ISSUE THREAD

**Issue by metadan** [kubernetes/website#16362] opened 2019-09-15 20:03 UTC
When attempting to run an app on a specific port the below is the result:

cmd: kubectl run kubernetes-bootcamp --image=gcr.io/google-samples/kubernetes-bootcamp:v1 --port=8080

response: _kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
deployment.apps/kubernetes-bootcamp created_

**Comment by BenHall** [comment] 2019-09-16 13:37
Thanks for the feedback @metadan 

We are currently planning how we can update the content to create into account this being removed. The reason for the delay is that with the new approach also needs to have a service created in order to access the application which isn't discussed until later in the course.

Duplicate of #15512

**Closed** 2019-09-18 15:59 UTC
Labels: triage/duplicate
