### ISSUE TITLE
Interactive Tutorial - Configuring a Java Microservice

### ISSUE THREAD

**Issue by moaismario** [kubernetes/website#38552] opened 2022-12-19 10:08 UTC
I had an issue in interactive tutorial (Step 1). when I ran command `mvn package -pl system` in terminal window I've got the error:
Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.10:build (default) on project system: Could not build image: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

**Comment by tamilselvan1102** [comment] 2022-12-19 11:26
/triage duplicate

This is a duplicate of issue https://github.com/kubernetes/website/issues/37994.

/kind bug
/language en

**Comment by mehabhalodiya** [comment] 2022-12-22 04:08
Per [this comment](https://github.com/kubernetes/website/issues/38552#issuecomment-1357497826), I am closing this issue. Thanks!

/close

**Closed by mehabhalodiya** 2022-12-22 04:08 UTC
Labels: kind/bug, triage/duplicate, language/en, needs-triage
