### ISSUE TITLE
Issue with k8s.io/docs/tasks/

### ISSUE THREAD

**Issue by MRDO5** [kubernetes/website#16259] opened 2019-09-08 08:25 UTC
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

Where is information or tasks ?

**Comment by sftim** [comment] 2019-09-09 13:52
This sounds like a duplicate of issue #16067

@MRDO5 was that what you wanted to see fixed?
/triage needs-information

**Comment by tengqm** [comment] 2019-12-01 04:34
pls feel free to open with actionable issue details or file a new one.

**Closed by tengqm** 2019-12-01 04:34 UTC
Labels: triage/needs-information
