### ISSUE TITLE
on-start.sh stuck in running - mongodB replica for second pod

### ISSUE THREAD

**Issue by kayalasomayajula** [kubernetes/website#14098] opened 2019-04-29 18:40 UTC
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by dbirks** [comment] 2019-04-29 19:25
Can you close this issue since it is a duplicate of #14099? Thank you.

**Closed** 2019-04-29 19:29 UTC
