### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/update-interactive/

### ISSUE THREAD

**Issue by sclausen** [kubernetes/website#5476] opened 2017-09-15 11:45 UTC
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
In 8/9 tries, the pods didn't came up.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by zacharysarah** [comment] 2017-09-19 22:20
@heckj :wave:

**Comment by heckj** [comment] 2017-09-20 01:33
thanks for the report @sclausen!

When you're saying the pods didn't come up, do you mean the initial pods never came active in the first section of the module (i.e. in step1 of 3), or was it later in the tutorial process (step 3 of 3 where we're rolling it back)?

Did you by chance capture the output of "kubectl get pods", or could you share the failure condition details here?

Part of step 3 of 3 is intentionally moving to where some failures occur to show how to "roll back". I'm not sure if you saw the errors and didn't realize they were intentional, or if something else was failing in the tutorial sequence.

Please let us know!

**Comment by sclausen** [comment] 2017-09-20 08:32
No, it was just at the beginning. Of course it works like a charm today, but back then `kubectl get deployments` showed most of the time the following (even if I waited for several seconds or tried multiple times in one instance)
```
  > kubectl get deployments                                                                  
No resources found.    
```
Sometimes ithe output command failed, with something like "can't connect to host01" or something similar. As I said, currently I can't reproduce it. The system must have been in a bad mood or something ;)

**Comment by heckj** [comment] 2017-09-21 02:59
Got it, thanks @sclausen 

/cc @BenHall

**Comment by BenHall** [comment] 2017-09-21 13:51
Thanks @sclausen. We'll keep an eye on this and see if we can reproduce it internally.

**Comment by heckj** [comment] 2017-10-23 20:14
@sclausen since this isn't an issue specific to updating the documentation, I'm going to go ahead and close this here. Thanks for letting us know!

**Closed by heckj** 2017-10-23 20:14 UTC
Labels: P2, team/katacoda
