### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by redcricket** [kubernetes/website#21071] opened 2020-05-19 19:36 UTC
**This is a Bug Report**

**Problem:**
I am not able to install kubeadm

I followed the instructions in the documentation yet I am not able to install the kubeadm RPM on my RHEL7 system.  Here is my /etc/yum.repos.d/kubernetes.repo

```
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
```

And when I execute (as root):

```
yum install -y kubelet kubeadm kubectl –disableexcludes=kubernetes
```

I get this output:

```
Loaded plugins: fastestmirror, langpacks, merge-conf, priorities, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Loading mirror speeds from cached hostfile
13024 packages excluded due to repository priority protections
No package kubelet available.
No package kubeadm available.
No package kubectl available.
Error: Nothing to do
```

The problem seem to be that the yum repo on the yum server does not have any packages.

If I point my browser to https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/Packages I see no RPMs listed.
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by neolit123** [comment] 2020-05-19 20:15
duplicate of https://github.com/kubernetes/kubernetes/issues/90158
please watch that ticket.

in the meantime i will try the install steps myself.

/close

**Closed** 2020-05-19 20:15 UTC
