### ISSUE TITLE
"Learn Kubernetes Basics" page still assumes we have an interactive online tutorial

### ISSUE THREAD

**Issue by shurup** [kubernetes/website#42505] opened 2023-08-11 14:24 UTC
**This is a Bug Report**

**Problem:** The "Kubernetes Basics" page still says things like «Each module contains [..] and includes an interactive online tutorial» and «The tutorials use Katacoda to run a virtual terminal in your web browser [..]». These statements are not valid anymore, and I guess they won't be fixed soon.

**Proposed Solution:** Change all related texts to reflect the actual instructions (for the "offline" terminal) we have now. I'm happy to fix them if that sounds reasonable.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/

/language en
/sig docs

**Comment by sftim** [comment] 2023-08-11 17:07
We should also remove the shortcode that renders as:

> ## Shutdown of interactive tutorials
> 
> The interactive tutorials on this website are being shut down. The Kubernetes project hopes to reinstate a similar interactive learning option in the long term.
> 
> The shutdown follows O'Reilly Media's 2019 [acquisition](https://www.oreilly.com/content/oreilly-acquires-katacoda-and-a-new-way-for-2-5m-customers-to-learn/) of Katacoda.
> 
> Kubernetes is grateful to O'Reilly and Katacoda for many years of helping people take their first steps in learning Kubernetes.
> 
> The tutorials will cease to function after the 31st of March, 2023. For more information, see "[Free Katacoda Kubernetes Tutorials Are Shutting Down](https://kubernetes.io/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/)."

**Comment by sftim** [comment] 2023-08-11 17:08
This is a duplicate of https://github.com/kubernetes/website/issues/42505
/triage duplicate

**Comment by sftim** [comment] 2023-08-11 17:14
/close

https://github.com/kubernetes/website/pull/41841 fixed #41836

**Closed by sftim** 2023-08-11 17:14 UTC
Labels: kind/bug, sig/docs, triage/duplicate, language/en, needs-triage
