### ISSUE TITLE
Advice about Service internal traffic policy

### ISSUE THREAD

**Issue by tamphuc0503** [kubernetes/website#46928] opened 2024-06-23 10:42 UTC
My kubernetes:
- 3 baremtals with 3 public ip (assume 180.1, 180.2,180.3)
- 
![image](https://github.com/kubernetes/website/assets/12606302/2c7c9069-87d6-4f77-83bb-827f72263351)

- deployed ingress nginx with daemonset to expose port 80/433
![image](https://github.com/kubernetes/website/assets/12606302/8664179a-4a3a-4254-998b-b2d8448cefd7)

Then, 
I create an API with Daemonsets to running API pods in all nodes with container port 8000.
Then, i create a service with Internal Traffic Policy is "Local" to hope that All http requests will lookup local pod (API pod in current node) first. 
Finally, i create ingress nginx with 3 host with 3 domains (these domain point to public ip by orders f1, f2,f3).
![image](https://github.com/kubernetes/website/assets/12606302/475822dd-1a9b-4866-93fd-48e9f4b0ca99)
But, when running healtcheckz API, (my api) wil return spec.nodename as env name. 
As documentation, internal traffic policy will make the request to f1.domain will be processed by "s1" node. but, healthcheck return server is "s3" or "s2" or "s1".

Is that a bug?

**Comment by dipesh-rawat** [comment] 2024-06-23 11:19
Looks like a request for help in its current form.

/kind support

**Comment by dipesh-rawat** [comment] 2024-06-23 11:19
@tamphuc0503 Thank you for reaching out and seeking assistance. We appreciate your query, but the GitHub issue tracker may not be the most suitable platform for obtaining advice on Kubernetes. We recommend exploring alternative resources such as the Kubernetes Slack community (http://slack.k8s.io/) or the Discuss Kubernetes forum (https://discuss.kubernetes.io/) for the support you need.

**Comment by sftim** [comment] 2024-06-23 14:58
/retitle Advice about Service internal traffic policy

However, if you want to report a Kubernetes bug @tamphuc0503 (especially one where you can explain how to reproduce it), please do file a report of the bug you've found.

**Comment by thisisharrsh** [comment] 2024-06-25 05:19
You can check if the internal traffic policy is correctly set to log local on the service. And ensure that the service is targeted at the correct pods.

**Comment by thisisharrsh** [comment] 2024-06-25 07:47
You can also verify the ingress rules are correctly configured and point to the correct service.

**Comment by niranjandarshann** [comment] 2024-07-03 07:09
Thank you for reaching out and seeking assistance. We appreciate your query, but the GitHub issue tracker may not be the most suitable platform for obtaining advice on Kubernetes. We recommend exploring alternative resources such as the Kubernetes Slack community (http://slack.k8s.io/) or the Discuss Kubernetes forum (https://discuss.kubernetes.io/) for the support you need. So For now i am closing this issue marking as unplanned 
/close

**Closed by niranjandarshann** 2024-07-03 07:09 UTC
Labels: kind/support, needs-triage
