### ISSUE TITLE
Running Multiple Instances of Your App - contradicting instructions

### ISSUE THREAD

**Issue by UnstoppableDrew** [kubernetes/website#46499] opened 2024-05-22 20:20 UTC
Under "Scaling an application" it says if you **didn't** delete the NodePort service from the previous section, delete it and expose the deployment with type LoadBalancer instead. Immediately below that is says if you **did** delete the NodePort, expose it as NodePort again. I'm assuming the second one is incorrect and you only want the LoadBalancer?

**Comment by dipesh-rawat** [comment] 2024-05-22 23:19
Page reported in issue: https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/scale-intro/
/language en

**Comment by dipesh-rawat** [comment] 2024-05-22 23:21
This appears to be a duplicate of existing issue https://github.com/kubernetes/website/issues/46429
/triage duplicate 
/kind bug

**Comment by dipesh-rawat** [comment] 2024-05-22 23:21
Closing in favor of https://github.com/kubernetes/website/issues/46429
/close not-planned

**Closed by dipesh-rawat** 2024-05-22 23:21 UTC
Labels: kind/bug, triage/duplicate, language/en, needs-triage
