### ISSUE TITLE
[hi] update the localization 

### ISSUE THREAD

**Issue by ranjan2829** [kubernetes/website#42589] opened 2023-08-16 17:03 UTC
![image](https://github.com/kubernetes/website/assets/73215366/9928d469-d14e-413b-b8b7-12ccfd7e88a4)

while seeing the index we can see that half objects are not localized

**Comment by sftim** [comment] 2023-08-16 17:12
/remove-triage accepted

This is a duplicate of https://github.com/kubernetes/website/issues/29353

/triage duplicate

**Comment by sftim** [comment] 2023-08-16 17:12
Please see the existing tracking issue @ranjan2829 

/close not-planned

**Closed by sftim** 2023-08-16 17:12 UTC
Labels: kind/feature, triage/duplicate, language/hi, needs-triage
