### ISSUE TITLE
Assigning Pods to Nodes

### ISSUE THREAD

**Issue by angelu721** [kubernetes/website#35150] opened 2022-07-19 02:49 UTC
in part of node-affinity, the example yaml file specific following condition:

      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
BUT, in part of describe area, it seems unmatched:

_**The node must have a label with the key topology.kubernetes.io/zone and the value of that label must be either antarctica-east1 or antarctica-west1.**_

does the nodeAffinity part means pod must be scheduled to node with label (kubernetes.io/os=linux) ?
It seems to have nothing to do with key topology.kubernetes.io/zone. Maybe I misunderstood this part.

**Comment by Rishit-dagli** [comment] 2022-07-19 05:49
This issue is a duplicate of #34573

**Comment by jihoon-seo** [comment] 2022-07-19 06:09
/triage duplicate

It seems that this is already resolved by the PR #34785.
It is likely that you are viewing somehow old version of this page, or certain localized page which is probably outdated.

Page: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity

[As-is]
![image](https://user-images.githubusercontent.com/46767780/179677082-49aa48a7-d25a-4190-8b09-5943e95b3aae.png)

**Closed** 2022-07-19 09:47 UTC
Labels: triage/duplicate, needs-triage
