### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/access-cluster-services/

### ISSUE THREAD

**Issue by hamshif** [kubernetes/website#7372] opened 2018-02-12 06:15 UTC
**This is a...** 

- [x ] Feature Request
- [ ] Bug Report

**Problem:
I need to be able to dynamically provide outer cluster clients [java script on browser] with the service's external IP without having a domain name. This is to enable any number of deployments for development, QA, staging and feature specific.

It is mentioned but not elaborated in Downward API
https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/

I couldn't find documentation about how to get a cluster's external ip from within a pod or deployment 
I couldn't find documentation about how to get a service's external ip from within a pod or deployment
**

**Proposed Solution:
If there is such a document then make it more readily searchable.

else if there is such a feature then document it and make it searchable.

else create such a feature through Downward API, document it and make it searchable.

**

**Page to Update:**
https://kubernetes.io/...

**Comment by zacharysarah** [comment] 2018-02-19 23:40
Duplicate of #7371, closing

**Closed by zacharysarah** 2018-02-19 23:40 UTC
