### ISSUE TITLE
Improvement for k8s.io/docs/tasks/access-application-cluster/web-ui-dashboard/

### ISSUE THREAD

**Issue by chadleywilson** [kubernetes/website#39510] opened 2023-02-17 12:07 UTC
Linux servers don't have gui, so these docs are only relevant to desktop gui users with experience.
The documentation assumes everyone is a student with a virtual host environment on a laptop.
I am a corporate engineer trying to learn how to use this is in a production environment and the documentation leaves me stranded.
I also can't find any guides with more info than what this  document offers. Maybe a bit explaining is needed so that I understand what I need to do next. Slack channels is dead nobody answers anything there. I have ask several questions albeit stupid to the more experienced users. But I need answers so that I can learn.

I need to setup ingress and can't work out how it works. I need a decent guide for that. None of the guides I have read are adaptable to getting this to work. Probably because nothing ties a whole solution together.

As a newbie running a headless system I cant access localhost in my web browser, Ok curl works, but I have no gui I need to access it from another machine and I have tried over and over with ingress and can't figure out what I must do.

**Comment by sftim** [comment] 2023-02-17 13:47
> Linux servers don't have gui, so these docs are only relevant to desktop gui users with experience.

I'm afraid that's untrue. You can access the web dashboard even when the GUI is on your computer and the web app is running somewhere else. As https://k8s.io/docs/tasks/access-application-cluster/web-ui-dashboard/ explains, you need a _web browser_ and the `kubectl` tool, already set up to access your cluster.

You could even use a Windows computer or a Mac to access the cluster, even when the cluster is Linux only.

If you're not able to run `kubectl` locally - ion other words, on the computer where you run your web browser and where you type commands etc, you'll need to find another way to make the dashboard available. I don't see this as a bug. However, there's an opportunity for someone to write a blog article - see https://blog.k8s.io/ - that helps less experienced cluster operators set things up for that situation.

**Comment by sftim** [comment] 2023-02-17 13:48
Also, if you don't have a web browser _at all_, the web UI is not going to be useful. That's also not a bug.

**Comment by chadleywilson** [comment] 2023-02-17 14:28
As I said you don't understand, the docs don't work.. here is why

ccwilson_admin@npe-kubemst-01:~/dashboard$ kubectl proxy
Starting to serve on 127.0.0.1:8001

I cannot get to that 127.0.0.1:8001, the server is headless and in London.
I am at home. I have configured DNS so that I can reach the server via FQDN over my VPN. And that's is working we have another release running on the server which we can access.


I am not reporting a bug, I commented on the documentation from the bottom of the page


This is supposed to make ingress work for the dashboard:

cat <<EOF | kubectl apply -f -
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: kubernetes-dashboard
  name: kubernetes-dashboard-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    # Uncomment next if you use https://cert-manager.io/
    #cert-manager.io/cluster-issuer: "<YOUR CLUSTER ISSUER>"
spec:
  tls:
  - hosts:
    - bw-npe.net
    secretName: kubernetes-dashboard-cert
  rules:
  - host: bw-npe.net
    http:
      paths:
      - path: /
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 80
EOF
error: unable to recognize "STDIN": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"

I don't how to fix that I am a newbie. I don't what that means, I can't google it, no body knows, and no one will answer any question on the newbie slack channel, and so I feel the documentation needs to cover this. 

 Can you tell me where I can go to get answers?

**Comment by sftim** [comment] 2023-02-17 15:51
There are some places you can turn for advice on Kubernetes. Try [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) - try the channel `#kubernetes-novice`, or to the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

Make sure you are running a [supported version](https://kubernetes.io/releases/) of Kubernetes.

**Comment by sftim** [comment] 2023-02-17 17:17
/kind support

I think

**Comment by tengqm** [comment] 2023-02-18 11:06
Looks like you have a misunderstanding about `kubectl proxy`. It is a command to run on your local host, not the remote node.

**Comment by chadleywilson** [comment] 2023-02-18 11:12
> Looks like you have a misunderstanding about `kubectl proxy`. It is a command to run on your local host, not the remote node.

Again you  clearly do not understand. The documentation only provides that as an option to access the dashboard.
But it can't be used on a headless system, I know what it is=, and how to use it.

So I need documentation on how to make the dashboard available via for example, nginx ingress


> There are some places you can turn for advice on Kubernetes. Try [Server Fault](https://serverfault.com/questions/tagged/kubernetes).
> 
> You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) - try the channel `#kubernetes-novice`, or to the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.
> 
> Make sure you are running a [supported version](https://kubernetes.io/releases/) of Kubernetes.

No one ever gets an answer on the novice group that's why I left it..

**Comment by tengqm** [comment] 2023-02-18 13:03
You are viewing the dashboard via a browser, right. The browser is not running on a headless box, that is for sure.
The dashboard is a service that feeds your browser with HTML, so the system that runs the dashboard service can be headless, and it typically runs on a remote node somewhere.
The whole k8s cluster can run on headless systems, but you can still access the Web UI from your local browser.
This has nothing to do with headless or not. Am I misunderstanding something?

**Comment by chadleywilson** [comment] 2023-02-18 17:09
Yes I know how web interfaces work.I have been building servers since 1998... 
Kubernetes is not like any ordinary server. Now after installation of the dashboard, I go to http://hostname/8001 <- supposedly the correct port for the dashboard.
 I get page not found. 
Now there is nothing in the document covering next steps.

I know I need to expose it via a service via nginx ingress. I clearly don't understand the documentation!  Becuase I just get errors. And you can't google those errors and get anything sensible. So for a novice there is no way to access it. The documents you provide only cover  running kubectl proxy. <- pay attention I have tried to tell you this 3 times now.
That is useless to me. I don't know how to get to the dashboard. Its seems to me it is obvious to everyone who is an Kubernetes expert. But to me I haven't got a clue and cannot figure out.

**Comment by sftim** [comment] 2023-02-18 19:49
Let's close this. I'm genuinely confident that the document is correct and is pitched right for the audience and their expected skill level.

You might like to watch https://youtu.be/NP8L8g1pjCQ?t=134 @chadleywilson which shows someone following that web page, running `kubectl proxy` on a computer that has a web browser installed. Remember, you **must** have a computer that runs a web browser to use the dashboard - but this computer doesn't have to run any other Kubernetes software than `kubectl`.

/close not-planned

**Closed** 2023-02-18 19:49 UTC
Labels: kind/support, needs-triage

**Comment by tengqm** [comment] 2023-02-19 01:13
I see. The communication to the dashboard seems okay. You are getting a 404 other than some other errors.
You may need some work on the Ingress then, if `kubectl proxy` works as expected.
