### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/kubernetes-basics/update/update-intro/

### ISSUE THREAD

**Issue by MAMware** [kubernetes/website#39472] opened 2023-02-15 10:48 UTC
the following text could use improvement, there are too many redudancies and ( ) should be avoided

Users expect applications to be available all the time and developers are expected to deploy new versions of them several times a day. In Kubernetes this is done with rolling updates. **Rolling updates allow Deployments' update to take place with zero downtime by incrementally updating Pods instances with new ones. The new Pods will be scheduled on Nodes with available resources.

In the previous module we scaled our application to run multiple instances. *This is a requirement for performing updates without affecting application availability. **By default, the maximum number of Pods that can be unavailable during the update and the maximum number of new Pods that can be created, is one.** Both options can be configured to either numbers or percentages (of Pods). In Kubernetes, updates are versioned and any Deployment update can be reverted to a previous (stable) version.

**Comment by Ritikaa96** [comment] 2023-02-15 17:22
/kind bug
/language en
Hi @MAMware , any contribution for improvement is welcome, you can raise a PR showing the changes you are proposing

**Comment by MAMware** [comment] 2023-02-16 14:09
#original
In the previous module we scaled our application to run multiple instances. This is a requirement for performing updates without affecting application availability. By default, the maximum number of Pods that can be unavailable during the update and the maximum number of new Pods that can be created, is one. Both options can be configured to either numbers or percentages (of Pods). In Kubernetes, updates are versioned and any Deployment update can be reverted to a previous (stable) version.

#proposed revision
In the previous module we scaled our application to run multiple instances. This is a requirement for performing updates without affecting application availability. By default, the maximum number of Pods that can be unavailable and can be created during the update, is one. Both options can be configured to either a fixed quantity or percentile of Pods. In Kubernetes, updates are versioned and any Deployment update can be reverted to a previous version.

**Comment by Ritikaa96** [comment] 2023-02-21 15:39
The issue #39493 is a duplicate of this issue so you can close that one and go through PR process using this issue.

**Comment by Ritikaa96** [comment] 2023-05-23 07:02
Hi @MAMware , is there any update for this one? you can close one issue among the two raised for same bug.

**Closed** 2024-01-18 23:59 UTC
Labels: kind/bug, lifecycle/rotten, language/en, needs-triage
