### ISSUE TITLE
Update to latest version of docsy

### ISSUE THREAD

**Issue by dtzar** [kubernetes/website#45410] opened 2024-03-01 18:20 UTC
**This is a Feature Request**
Update to the latest version of docsy.  There are [significant breaking changes when the project switches to bootstrap v5.](https://www.docsy.dev/blog/2023/bootstrap-5-migration/).  

Optional consideration with this feature update - use the latest recommended pattern with docsy to [install with go modules ](https://www.docsy.dev/docs/get-started/docsy-as-module/) versus git submodules. 

I really believe we need to have someone get an updated hugo/docsy template with the latest docsy version which works with various features, especially the https://github.com/google/docsy-example/issues/254.

Related sig meeting discussion in case others care to know more. 
[CNCF Tech Docs office hours](https://docs.google.com/document/d/1roexHTLCrErYjNT2NEoRsVnn_YNbQzZ1gyXNK8hXR4Q/edit#heading=h.f19hbaugtdtu)

**Why is this needed**
To continue to keep up with code fixes/enhancements of the documentation website.

```[tasklist]
### Tasks
```

**Comment by sftim** [comment] 2024-03-01 18:30
Ah, this is actually almost a duplicate of https://github.com/kubernetes/website/issues/44002

/triage duplicate
/remove-priority important-longterm

Thanks for filing it anyway!

**Closed** 2024-03-06 01:42 UTC
Labels: kind/feature, triage/duplicate, area/web-development, needs-triage
