### ISSUE TITLE
Minikube stop FAILS

### ISSUE THREAD

**Issue by ariamore** [kubernetes/website#13571] opened 2019-04-02 12:55 UTC
I've a problem when I try to stop minikube. I run the command (on Powershell, using Windows 10):
$ minikube stop
and the machine remains in a "pending" state for several time, like the image below

![Cattura](https://user-images.githubusercontent.com/46370083/55403793-e6d86300-5556-11e9-9e30-bb07debd519f.PNG)

I've got the same result if I check the status of minikube on Hyper (I'm using this virtual-switch).
I already tried the instruction $ minikube ssh | sudo poweroff     (and this workaround works!);
but I wanna know if someone is able to solve in another way or if is able to explain which is the real problem! 

Thanks in advance!

**Comment by tstromberg** [comment] 2019-04-02 20:46
Dupe of https://github.com/kubernetes/minikube/issues/2914

**Comment by tengqm** [comment] 2019-04-05 04:38
@tstromberg Thanks for pointing that out. Closing this because it is not a doc issue.

**Closed by tengqm** 2019-04-05 04:38 UTC

**Comment by jjfraney** [comment] 2019-04-05 13:21
Also, same problem with **minikube 1.0.0.**  Stop hangs.

However, the added information I offer is that docker-machine, included with Docker Desktop, can start and stop vm clients on hyperv.  I've built a three node docker swarm with docker-machine from Docker Desktop...and stopped the nodes, too.

Here is version of Docker Desktop I'm running:
Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3
