### ISSUE TITLE
Releases Documentation missing kubernetes release version 1.28.8

### ISSUE THREAD

**Issue by gopikishanm** [kubernetes/website#45796] opened 2024-04-07 23:33 UTC
The kubernetes release documentation does not contain details about 1.28.8 release version. It is present on changelog file

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md

**Comment by dipesh-rawat** [comment] 2024-04-08 06:51
This looks duplicate of an issue we already have #45668

/triage duplicate

**Comment by niranjandarshann** [comment] 2024-04-08 09:58
@gopikishanm Thank you for pointing this out, The issue is already raised. If you are  raising some issue so first try to find whether the issue is already raised in community. If it is raised then please dont raise the duplicate issue.
Keep working. Appriciate your point of view.

**Comment by niranjandarshann** [comment] 2024-04-08 09:59
The issue is already raised so I am closing this issue and  You may reopen it if you find something more and point to be raised for solving it.
/close

**Closed by niranjandarshann** 2024-04-08 10:00 UTC
Labels: triage/duplicate, needs-triage
