### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

### ISSUE THREAD

**Issue by turanmehmet** [kubernetes/website#28000] opened 2021-05-16 11:41 UTC
Documentation needs to be upgrade a Kubernetes cluster created with kubeadm from version 1.19.x to version 1.20.x 
https://v1-20.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

**Comment by neolit123** [comment] 2021-05-17 15:03
duplicate of:
https://github.com/kubernetes/website/issues/27525

/sig cluster-lifecycle
/close

**Closed** 2021-05-17 15:04 UTC
Labels: help wanted, sig/cluster-lifecycle, triage/accepted
