### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/pods/init-containers/

### ISSUE THREAD

**Issue by Davidrjx** [kubernetes/website#12681] opened 2019-02-18 05:20 UTC
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
pod sample yaml with init containers is confusing where until cmd string always is executed successfully at my side.

**Proposed Solution:**
change until to a more general one

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

**Comment by sftim** [comment] 2019-02-19 12:39
Is this similar to / a duplicate of  #12050 ?

**Comment by DanyC97** [comment] 2019-02-27 10:55
sounds like it @sftim (i don't have the _power_ to close it)

**Comment by DanyC97** [comment] 2019-03-21 23:35
/close

as being duplicate of #12050

**Closed by DanyC97** 2019-03-21 23:35 UTC
