### ISSUE TITLE
Broken link on Glossary page

### ISSUE THREAD

**Issue by kadtendulkar** [kubernetes/website#35642] opened 2022-08-02 16:19 UTC
**Problem:**
The text [**Code Contributor**](https://kubernetes.io/docs/community/devel/) on [link](https://kubernetes.io/docs/reference/glossary/) is not working, it should point to these https://kubernetes.io/docs/reference/glossary/?user-type=true#term-code-contributor

Check the page [Glossary](https://kubernetes.io/docs/reference/glossary/) for the problem.

**Page to Update:**
https://kubernetes.io/docs/reference/glossary/

**Proposed Solution:**
It should resolve this issue by adding a simple link and enhancing the document line.
Update the link on the texts Code Contributor to https://kubernetes.io/docs/reference/glossary/?user-type=true#term-code-contributor and not to this [link](https://kubernetes.io/docs/community/devel/).

/kind document
/assign
/language en

**Comment by amolmote** [comment] 2022-09-15 06:12
duplicate triage this issue will fix it #36773

**Comment by mtardy** [comment] 2022-09-15 08:05
Hey, thanks for amolmote to notice, I created an issue that was a duplicate of this one, there is some more information available there [Broken link in glossary entry code-contributor #36773](https://github.com/kubernetes/website/issues/36773). I'll mark this one as a good first issue as well and put the previously assigned person.

/triage accepted
/good-first-issue
/assign amolmote

**Comment by mtardy** [comment] 2022-09-15 08:07
Oh, I just noticed that @kadtendulkar already assign themselves on this issue. Since it's been a bit more than two months, please tell amolmote if you are still working on this one or if it's okay that they take over.

**Closed** 2022-09-19 22:29 UTC
Labels: good first issue, help wanted, kind/bug, language/en, triage/accepted
