### ISSUE TITLE
Issue with k8s.io/docs/tasks/service-catalog/install-service-catalog-using-helm/

### ISSUE THREAD

**Issue by lonial** [kubernetes/website#20461] opened 2020-04-20 19:53 UTC
helm install command for service catalog is giving me below error and I am trying this command with helm 3 install with minikube version: v1.9.0.

Could you please verify if this command is correct and there is no need to do changes for API version in charts?

helm install catalog svc-cat/catalog --namespace catalog

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by prasadkatti** [comment] 2020-04-20 20:53
The api group `extensions/v1beta1` is no longer served in 1.18. Check #19996.

**Comment by prasadkatti** [comment] 2020-04-20 20:59
An issue has been created for this - https://github.com/kubernetes-sigs/service-catalog/issues/2787

**Comment by prasadkatti** [comment] 2020-04-20 21:13
You can try to install [v0.3.0-beta.2](https://github.com/kubernetes-sigs/service-catalog/releases/tag/v0.3.0-beta.2). That has the fix for this issue.

**Comment by prasadkatti** [comment] 2020-04-20 21:17
Or you can install service-catalog from master using the instructions from this comment -
https://github.com/kubernetes-sigs/service-catalog/issues/2787#issuecomment-602693192

**Comment by mszostok** [comment] 2020-05-25 19:17
Hi @lonial 

The website is a little bit out-dated.  This will be fixed in this issue: https://github.com/kubernetes-sigs/service-catalog/issues/2633

For now you can visit https://svc-cat.io/ site to get up to date information on how to run Service Catalog.

Today we released the [0.3.0 version](https://github.com/kubernetes-sigs/service-catalog/releases/tag/v0.3.0) which supports also the k8s 1.18 version.

**Comment by tengqm** [comment] 2020-06-14 12:44
So it turned out to be the chart using only API resources and the problem is fixed upstream.
There doesn't seem anything to do from docs side.
/close

**Closed** 2020-06-14 12:44 UTC
