### ISSUE TITLE
Hyperlink broken

### ISSUE THREAD

**Issue by mohi048** [kubernetes/website#13440] opened 2019-03-26 11:34 UTC
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
On page - https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/

the spec format for a Deployment object can be found **here**

points to https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#deploymentspec-v1-apps

This url does not works.

**Proposed Solution:**
Fix hyperlink - https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#deploymentspec-v1-apps

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/

**Comment by DanyC97** [comment] 2019-03-26 13:38
@mohi048 thank you for raising the issue.

i think this is all caused by https://github.com/kubernetes/website/issues/13396 which should be fixed shortly

**Comment by tengqm** [comment] 2019-03-27 06:04
Should have been fixed. Closing.

**Closed by tengqm** 2019-03-27 06:04 UTC
