### ISSUE TITLE
Install and Set Up kubectl on Windows

### ISSUE THREAD

**Issue by DarshanUmapathi** [kubernetes/website#44333] opened 2023-12-13 18:35 UTC
The download link for windows is not working

**Comment by dipesh-rawat** [comment] 2023-12-13 18:47
Looks like a duplicate of issue https://github.com/kubernetes/website/issues/44330 we got earlier
/triage duplicate

**Comment by T-Lakshmi** [comment] 2023-12-13 18:47
Page: https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/#install-kubectl-binary-with-curl-on-windows
/language en
/sig docs

**Comment by sftim** [comment] 2023-12-14 09:07
/close
Fixed in #44330

**Closed by sftim** 2023-12-14 09:07 UTC
Labels: sig/docs, triage/duplicate, language/en, needs-triage
