### ISSUE TITLE
Can create new instance in session

### ISSUE THREAD

**Issue by SirRanger** [kubernetes/website#38184] opened 2022-11-30 07:30 UTC
I can click add new instance button but nothing is happening.

Chrome dev-tool; Networkmonitor says this:

Requested-URL: https://labs.play-with-k8s.com/sessions/ce3g765er0q000deog10/instances
Request method: POST
Statuscode: 500 
Remoteadresse: 52.233.186.82:443
Referrer-Richtlinie: strict-origin-when-cross-origin

**Comment by Ritikaa96** [comment] 2022-11-30 10:56
@SirRanger I think this is similar to [this](https://github.com/play-with-docker/play-with-kubernetes.github.io/issues/42) issue
I have tried replicating the issue but I can create new instances easily. For reference , please see the image below.[](url)

![Screenshot from 2022-11-30 16-24-11](https://user-images.githubusercontent.com/52399571/204778175-ced2677c-1fc9-4835-8175-e93b7b82a5fb.png)

/kind support

**Comment by Ritikaa96** [comment] 2022-11-30 11:05
The last time this issue occured play-with-k8s team stated it was down at the time, this issue can be due to 
- network issue
- site loading / site is down
- pop blocker is enabled
- browser window size isn't right , so need to resize the browser window in that case.

**Comment by Ritikaa96** [comment] 2023-03-02 08:11
If the issue no longer exist we can close this one. @SirRanger Please confirm

**Comment by Ritikaa96** [comment] 2023-04-01 09:40
@SirRanger As there havent been any response and the issue is 
/triage not-reproducible
I'm closing this issue
/close

**Closed by Ritikaa96** 2023-04-01 09:40 UTC
Labels: lifecycle/rotten, triage/not-reproducible, kind/support, needs-triage
