### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/high-availability/

### ISSUE THREAD

**Issue by ocofaigh** [kubernetes/website#9073] opened 2018-06-14 09:46 UTC
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
There is a broken link on this page: https://kubernetes.io/docs/setup/independent/high-availability/#set-up-master-load-balancer

It is under the heading "Run kubeadm init on master0"

This is the line with the broken link (in bold):
<virtual-ip> with the virtual IP. Please read **setting up a master load balancer** section of the docs for more information.

**Proposed Solution:**
Fix the broken link

**Page to Update:**
https://kubernetes.io/docs/setup/independent/high-availability/

**Comment by jimangel** [comment] 2018-06-19 01:08
It looks like this is being worked on: [#9034](https://github.com/kubernetes/website/issues/9034)

**Comment by neolit123** [comment] 2018-06-19 03:15
/close
duplicate of #9034

**Closed by neolit123** 2018-06-19 03:15 UTC
