### ISSUE TITLE
Issue with k8s.io/docs/concepts/scheduling-eviction/assign-pod-node/

### ISSUE THREAD

**Issue by erhhung** [kubernetes/website#34767] opened 2022-07-02 03:53 UTC
Description of Node Affinity example pod spec "pods/pod-with-node-affinity.yaml" contains an error:

> "The node must have a label with the key `topology.kubernetes.io/zone` and the value of that label must be either `antarctica-east1` or `antarctica-west1`."

does not apply. The spec shows instead that key "`kubernetes.io/os`" should be "`linux`".

Under the Node Affinity Weight section, the following note is also out-of-place:

> "Note: If you want Kubernetes to successfully schedule the Pods in this example, you must have existing nodes with the `kubernetes.io/os=linux label`."

It needs to be moved to the previous section.

**Comment by jihoon-seo** [comment] 2022-07-03 06:39
This issue is a duplicate of #34573.
/triage duplicate

**Closed** 2022-07-16 14:46 UTC
Labels: triage/duplicate, needs-triage
