### ISSUE TITLE
Existing links to Kubernetes documentation no longer working

### ISSUE THREAD

**Issue by malikperang** [kubernetes/website#33227] opened 2022-04-26 17:58 UTC
Several pages are broken.

https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-application/

**Comment by sftim** [comment] 2022-04-26 18:13
/retitle Existing links to Kubernetes documentation no longer working

This looks to have been caused by PR #32823.
/kind bug
/language en
/triage accepted

**Comment by jihoon-seo** [comment] 2022-06-07 23:52
This issue has been resolved by the PR #33220.
And I confirm that in `content/en/`, there exists no link that points to `debug-application-cluster/**.md`.
/close

**Closed** 2022-06-07 23:52 UTC
Labels: kind/bug, language/en, triage/accepted

**Comment by Babapool** [comment] 2022-06-08 04:14
I would like to work on this issue. Thanks.
/assign

**Comment by Babapool** [comment] 2022-06-08 04:26
@jihoon-seo The `Whats Next` section of the https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/ is leading to 404 error. Could please double check it and if the error is there, can I go ahead and work on the issue?

**Comment by jihoon-seo** [comment] 2022-06-08 04:52
@Babapool Yes I see 404 too. Please go ahead!

[Suggestions]
In `content/en/docs/tasks/debug/debug-application/debug-service.md`

```diff
-[Slack](/docs/tasks/debug/overview/#slack) or
+[Slack](https://slack.k8s.io/),

-Visit the [troubleshooting overview document](/docs/tasks/debug/overview/)
+Visit the [troubleshooting overview document](/docs/tasks/debug/)
```

**Comment by Babapool** [comment] 2022-06-08 04:54
Sure I will create a new issue and label it as good first issue so that new contributors can work on it :)

**Comment by Babapool** [comment] 2022-06-08 05:15
Created a new issue 👍  . Thanks @jihoon-seo
