### ISSUE TITLE
Improvement for k8s.io/docs/tasks/tls/certificate-rotation/

### ISSUE THREAD

**Issue by networkandcode** [kubernetes/website#15240] opened 2019-07-02 09:39 UTC
Is this option deprecated

--rotate-certificates                        <Warning: Beta feature> Auto rotate the kubelet client certificates by requesting new certificates from the kube-apiserver when the certificate expiration approaches. (DEPRECATED: This parameter should be set via the config file specified by theKubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.)

Could you provide the procedure for setting kubelet certificate rotation through the config file

**Comment by sftim** [comment] 2019-09-10 22:51
This looks like a close duplicate of #13928

**Comment by sftim** [comment] 2019-09-10 22:51
Is it OK to close this one?

**Closed** 2019-10-11 05:59 UTC
