### ISSUE TITLE
Configure Access to Multiple Clusters: link to Katacoda is no longer valid

### ISSUE THREAD

**Issue by gmacario** [kubernetes/website#34662] opened 2022-06-28 10:05 UTC
The page linked from "Katacoda" (<https://www.katacoda.com/courses/kubernetes/playground>) on page <https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/> returns

![image](https://user-images.githubusercontent.com/75182/176152929-4ffc384e-c3ea-4986-bdaa-828d691b426d.png)

**Comment by NitishKumar06** [comment] 2022-06-28 10:23
This [PR](https://github.com/kubernetes/website/pull/34496) actually fixes this issue. We have tried to remove Katacoda and replaced it with [Killercoda](https://killercoda.com/playgrounds). That PR is under review . Although the changes look good according to @reylejano .

**Comment by sftim** [comment] 2022-06-28 10:43
Duplicate of issue https://github.com/kubernetes/website/issues/34428

/triage duplicate

**Comment by jihoon-seo** [comment] 2022-08-17 22:20
This issue has been resolved by the PR #34429.
/close

**Closed** 2022-08-17 22:20 UTC
Labels: triage/duplicate, needs-triage
