### ISSUE TITLE
Issue with deployment of mysql-deployment using minikube

### ISSUE THREAD

**Issue by stretchcloud** [kubernetes/website#6035] opened 2017-10-24 19:01 UTC
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
When deploying MySQL using minikube, getting this error.

$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-10-06T20:53:14Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl create -f mysql-deployment.yaml
service "wordpress-mysql" created
persistentvolumeclaim "mysql-pv-claim" created
**Error from server (BadRequest): error when creating "mysql-deployment.yaml": Deployment in version "v1beta2" cannot be handled as a Deployment: no kind "Deployment" is registered for version "apps/v1beta2"**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/

**Comment by heckj** [comment] 2017-10-25 18:30
/cc @steveperry-53 

I'm suspecting you saw this or were amazingly prescient during last docs meeting - this applies directly to what you were calling out in terms of specific versions and their implications on our "always published" docs.

The above content *does* expect a 1.8 cluister, but we 1) don't it out and 2) likely could have kept it at it's earlier version that would still (I think?) work with a past alias to the same API endpoint

Complicating the issue is that minikube still only supports a default of creating 1.7.5 clusters even after the 1.8 release (per https://github.com/kubernetes/minikube/issues/2020)

**Comment by heckj** [comment] 2018-01-10 21:40
comments about version dependencies are now in the example YAML, so I'm closing this out

**Closed by heckj** 2018-01-10 21:40 UTC
Labels: Docs Review: Open Issues, P2
