### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by biello** [kubernetes/website#17924] opened 2019-12-03 09:24 UTC
**This is a Bug Report**
following the guide [Configure cgroup driver used by kubelet on control-plane node](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#configure-cgroup-driver-used-by-kubelet-on-control-plane-node), 
use systemd as docker cgroup driver, write KUBELET_EXTRA_ARGS=--cgroup-driver=systemd to /etc/sysconfig/kubelet but doesn't work.

**Problem:**
kubelet cannot start
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#configure-cgroup-driver-used-by-kubelet-on-control-plane-node

OS: CentOS7.2 with kernel: Linux 3.10.0-514.26.2.el7.x86_64

`docker info -f {{.CgroupDriver}}`
systemd

`cat /etc/sysconfig/kubelet`
KUBELET_EXTRA_ARGS=--cgroup-driver=systemd

`journalctl -xeu kubelet`
-- Unit kubelet.service has begun starting up.
12月 03 11:07:34 k8s-master-01 kubelet[4811]: I1203 11:07:34.991782    4811 server.go:410] Version: v1.16.3
12月 03 11:07:34 k8s-master-01 kubelet[4811]: I1203 11:07:34.992033    4811 plugins.go:100] No cloud provider specified.
12月 03 11:07:34 k8s-master-01 kubelet[4811]: W1203 11:07:34.992048    4811 server.go:549] standalone mode, no API client
12月 03 11:07:35 k8s-master-01 kubelet[4811]: W1203 11:07:35.016308    4811 server.go:467] No api server defined - no events will be sent to API server.
12月 03 11:07:35 k8s-master-01 kubelet[4811]: I1203 11:07:35.016327    4811 server.go:636] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
12月 03 11:07:35 k8s-master-01 kubelet[4811]: I1203 11:07:35.016614    4811 container_manager_linux.go:265] container manager verified user specified cgroup-root exists: []
12月 03 11:07:35 k8s-master-01 kubelet[4811]: I1203 11:07:35.016627    4811 container_manager_linux.go:270] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroup
12月 03 11:07:35 k8s-master-01 kubelet[4811]: I1203 11:07:35.016722    4811 fake_topology_manager.go:29] [fake topologymanager] NewFakeManager
12月 03 11:07:35 k8s-master-01 kubelet[4811]: I1203 11:07:35.016728    4811 container_manager_linux.go:305] Creating device plugin manager: true
12月 03 11:07:35 k8s-master-01 kubelet[4811]: I1203 11:07:35.016749    4811 fake_topology_manager.go:39] [fake topologymanager] AddHintProvider HintProvider:  &{kubelet.sock /var/lib/kubelet/device
12月 03 11:07:35 k8s-master-01 kubelet[4811]: I1203 11:07:35.016789    4811 state_mem.go:36] [cpumanager] initializing new in-memory state store
12月 03 11:07:35 k8s-master-01 kubelet[4811]: I1203 11:07:35.016878    4811 state_mem.go:84] [cpumanager] updated default cpuset: ""
12月 03 11:07:35 k8s-master-01 kubelet[4811]: I1203 11:07:35.016888    4811 state_mem.go:92] [cpumanager] updated cpuset assignments: "map[]"
12月 03 11:07:35 k8s-master-01 kubelet[4811]: I1203 11:07:35.016898    4811 fake_topology_manager.go:39] [fake topologymanager] AddHintProvider HintProvider:  &{{0 0} 0x79a0338 10000000000 0xc00086
12月 03 11:07:35 k8s-master-01 kubelet[4811]: I1203 11:07:35.019422    4811 client.go:75] Connecting to docker on unix:///var/run/docker.sock
12月 03 11:07:35 k8s-master-01 kubelet[4811]: I1203 11:07:35.019448    4811 client.go:104] Start docker client with request timeout=2m0s
12月 03 11:07:35 k8s-master-01 kubelet[4811]: W1203 11:07:35.024960    4811 docker_service.go:563] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth
12月 03 11:07:35 k8s-master-01 kubelet[4811]: I1203 11:07:35.024987    4811 docker_service.go:240] Hairpin mode set to "hairpin-veth"
12月 03 11:07:35 k8s-master-01 kubelet[4811]: W1203 11:07:35.025085    4811 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
12月 03 11:07:35 k8s-master-01 kubelet[4811]: I1203 11:07:35.029419    4811 docker_service.go:255] Docker cri networking managed by kubernetes.io/no-op
12月 03 11:07:35 k8s-master-01 kubelet[4811]: I1203 11:07:35.037545    4811 docker_service.go:260] Docker Info: &{ID:4PTN:INQG:E7GI:RHP6:2Y4D:MUR4:ZGFP:UEOF:LNNW:GDOM:WCIR:LTT5 Containers:0 Contain
12月 03 11:07:35 k8s-master-01 kubelet[4811]: F1203 11:07:35.037650    4811 server.go:271] failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "cgroupfs" is di
12月 03 11:07:35 k8s-master-01 systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
12月 03 11:07:35 k8s-master-01 systemd[1]: Unit kubelet.service entered failed state.
12月 03 11:07:35 k8s-master-01 systemd[1]: kubelet.service failed.

**Comment by neolit123** [comment] 2019-12-03 21:15
> run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "cgroupfs" is di

it seems you are not passing the cgroup driver correctly.
also, in the case of docker you don't need to pass the flag.

kubeadm should autodetect the cgroup driver.

try removing:
> KUBELET_EXTRA_ARGS=--cgroup-driver=systemd

/triage support

**Comment by biello** [comment] 2019-12-04 02:49
> the

thanks, it seems kubelet failed to autodetect the cgroup driver of docker.
I tried to remove /etc/sysconfig/kubelet, /etc/systemd/system/kubelet.service.d/10-kubeadm.conf，
but doesn't work, journalctl -xeu kubelet output all the same.

**Comment by biello** [comment] 2019-12-04 02:58
is my docker version 18.06.2-ce too old for autodetection?

**Comment by neolit123** [comment] 2019-12-04 03:23
> thanks, it seems kubelet failed to autodetect the cgroup driver of docker.

kubeadm is responsible for autodetecting the docker version and it passes the matching --cgroup-driver flag to the kubelet when you call `kubeadm init` or `kubeadm join`.

>  /etc/systemd/system/kubelet.service.d/10-kubeadm.conf，

if you have deleted this file you need to re-install the kubelet package.

> is my docker version 18.06.2-ce too old for autodetection?

this version is supported.

**Comment by biello** [comment] 2019-12-04 03:54
I reinstalled kubelet and checked this file `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` is empty, and run  `kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=myip`, it says 
`The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
Unfortunately, an error has occurred:
	timed out waiting for the condition

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'`

so i turn to check `journalctl -xeu kubelet`, and it says
`failed to create kubelet: misconfiguration: kubelet cgroup driver: "cgroupfs" is different from docker cgroup driver: "systemd"`

apparently it's the cgroup driver problem, the problem is how can i set kubelet cgroup driver to  "systemd" as k8s recommanded? Or how can i let kubeadm know that my docker cgroup driver is "systemd"?

**Comment by biello** [comment] 2019-12-04 04:03
is there any problem with my OS, docker or something else? Or is it a bug of kubeadm or kubelet?

**Comment by neolit123** [comment] 2019-12-04 14:52
> /etc/systemd/system/kubelet.service.d/10-kubeadm.conf 

this file should not be empty for the kubelet to work.
try uninstalling kubeadm and kubelet and installing them again.

**Comment by biello** [comment] 2019-12-05 02:50
thx, I uninstalled kubeadm and kubelet with `yum remove`, and then installed them with `yum install`, but this file `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` is still empty, any idea?

**Comment by neolit123** [comment] 2019-12-05 03:48
did you try removing the file first, before installing the packages?
i don't see how after package installation the file will be empty.

closing as not a bug or documentation change request.

/close

**Closed by neolit123** 2019-12-05 03:48 UTC
Labels: sig/cluster-lifecycle, triage/support
