### ISSUE TITLE
Installing kubeadm - sysctl error

### ISSUE THREAD

**Issue by AndrewSav** [kubernetes/website#26503] opened 2021-02-14 06:07 UTC
This [section](https://github.com/kubernetes/website/blob/2e78b33f62dd486c235a5b5668fa612ab8c22f36/content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md#letting-iptables-see-bridged-traffic) of the "Installing kubeadm" page gives this command to run: `sudo sysctl --system`. On Ubuntu 20.04 this line produces the following error:

```text
 "sysctl: setting key "net.ipv4.conf.all.promote_secondaries": Invalid argument"
```
There was a corresponding issue opened [here](https://github.com/systemd/systemd/issues/17156), which was then closed saying "you should not use sysctl on systems running systemd".

It sounds like the documentation needs to be updated to reflect that.

**Comment by neolit123** [comment] 2021-02-14 17:30
/sig cluster-lifecycle network
/priority awaiting-more-evidence

i can confirm the error message for the `net.ipv4.conf.all.promote_secondaries`
but for me the overall command `sudo sysctl --system` has an exit status of 0 (success).

i have a couple of questions:
- why should we worry about https://sysctl-explorer.net/net/ipv4/promote_secondaries/ , i don't think this is a blocking problem?
- what should we replace `sudo sysctl --system` with?

the [linked issue](https://github.com/systemd/systemd/issues/17156) talks about:
> It is rather strange to use sysctl when you have systemd-sysctl installed on the same system

but it's unclear to me how to use systemd-sysctl.

**Comment by AndrewSav** [comment] 2021-02-14 18:34
> why should we worry about https://sysctl-explorer.net/net/ipv4/promote_secondaries/ , i don't think this is a blocking problem?

I have no idea. If this message is benign and can be ignored the documentation need to say so. Someone needs to confirm that this is the case

> what should we replace sudo sysctl --system with?

I have no idea. As a kubernetes user I stumble upon the described behaviour when I try to install a kubernetes cluster as per the documentation. I need help resolving this.

> but it's unclear to me how to use systemd-sysctl.

Yes, this is basically is the essence of what this issues is about.

**Comment by neolit123** [comment] 2021-02-14 19:49
@AndrewSav 

the sysctl call works. as much as the systemd issue talks about that sysctl should not be used, i think we are entering the land of distro specifics, which we would like to avoid.

> Yes, this is basically is the essence of what this issue is about - it is utterly unclear. This needs to be clarified.

i just tried calling `/usr/lib/systemd/systemd-sysctl` and it throws some errors too:

```
Not setting net/ipv4/conf/all/promote_secondaries (explicit setting exists).
Not setting net/ipv4/conf/default/promote_secondaries (explicit setting exists).
```

reading here:
https://bbs.archlinux.org/viewtopic.php?id=258073

i can confirm the setting already exists on 20.04 in `/usr/lib/sysctl.d/50-default.conf`
since we are not managing promote_secondaries in the kubeadm docs, this is a distro / bridge-nf problem.

```
Couldn't write '1' to 'net/bridge/bridge-nf-call-ip6tables', ignoring: No such file or directory
Couldn't write '1' to 'net/bridge/bridge-nf-call-iptables', ignoring: No such file or directory
```

this is not a problem if calling `sysctl --system`

reading here:
https://bugzilla.redhat.com/show_bug.cgi?id=1264588
the thread is vague on why it's happening.

@aojea do you know if its actually not setting the filter in such cases?

**Comment by aojea** [comment] 2021-02-14 20:06
> @aojea do you know if its actually not setting the filter in such cases?

I can't reproduce it, but you'll be able to query the key value with
```
$ sudo sysctl net.bridge.bridge-nf-call-iptables
net.bridge.bridge-nf-call-iptables = 1
```

> i think our guide [here](https://github.com/kubernetes/website/blob/2e78b33f62dd486c235a5b5668fa612ab8c22f36/content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md#letting-iptables-see-bridged-traffic) sets the bridged traffic for v4/v6 despite the warnings from `sysctl`

**Comment by neolit123** [comment] 2021-02-14 20:12
ok, i can confirm that our `sysctl --system` command sets everything that we care about properly despite the warning about `promote_secondaries`. `/usr/lib/systemd/systemd-sysctl` is the recommended tool, but it's actually more confusing since it prints more vague errors.

closing
/close

**Closed** 2021-02-14 20:12 UTC
Labels: needs-triage, priority/awaiting-more-evidence, sig/cluster-lifecycle, sig/network

**Comment by AndrewSav** [comment] 2021-02-14 22:58
@neolit123 So you do not think it's worse clarifying this in the documentation? You think it is okay that the steps outlined in the doco produce a error and the doco does not make it clear, that the error can be safely ignored?

**Comment by neolit123** [comment] 2021-02-15 01:06
yes, this error can be ignored.

**Comment by AndrewSav** [comment] 2021-02-15 01:29
@neolit123 Is it worth updating kubernetes documentation to reflect that?

**Comment by neolit123** [comment] 2021-02-15 01:38
i don't think so.
it's just noise from the tooling and promote_secondaries is already set in 50-default.conf for 20.04.

**Comment by 0xdreadnaught** [comment] 2021-12-26 05:48
> i don't think so. it's just noise from the tooling and promote_secondaries is already set in 50-default.conf for 20.04.

For people that are completely new to K8, it's a rabbit hole that could easily be squashed with a 2 sentence commit.
