### ISSUE TITLE
"Using kubectl to Create a Deployment" tutorial doesn't work on ARM64 architecture

### ISSUE THREAD

**Issue by FiredPhoenixIR** [kubernetes/website#44379] opened 2023-12-15 16:06 UTC
Following instructions in https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

kubectl create deployment kubernetes-bootcamp --image=gcr.io/google-samples/kubernetes-bootcamp:v1

kubectl logs kubernetes-bootcamp-f95c5b745-l2422 :
exec /bin/sh: exec format error

describe pod:
Warning  BackOff    76s (x10 over 3m17s)  kubelet            Back-off restarting failed container kubernetes-bootcamp in pod kubernetes-bootcamp-879b87896-tgg2t_default(5d4f303b-072a-4660-bfe5-c2998fb5dea4)

![image](https://github.com/kubernetes/website/assets/84761387/0d762cd4-fcfe-404e-8e2f-fd836fd3ad34)

**Comment by FiredPhoenixIR** [comment] 2023-12-15 16:18
used this image for now and it's working as I'm on a ARM64 host: https://hub.docker.com/r/baniyuga/kubernetes-bootcamp

**Comment by dipesh-rawat** [comment] 2023-12-15 16:21
@FiredPhoenixIR Could please confirm the you are following the tutorial documentation in the webpage https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/? It would be nice to mention the page in the [issue description (here)](https://github.com/kubernetes/website/issues/44379#issue-2043984729).

**Comment by dipesh-rawat** [comment] 2023-12-16 00:46
/retitle "Using kubectl to Create a Deployment" tutorial doesn't work on ARM64 architecture
(To provide a more general perspective.)

/language en

**Comment by adityasamant25** [comment] 2023-12-16 12:37
This is a duplicate of #44271

**Comment by kundan2707** [comment] 2023-12-18 04:51
I tried on Architecture: x86_64
its working fine to me

**Comment by kumarankit999** [comment] 2023-12-18 06:17
Yes, it also working fine x86_64

**Comment by adityasamant25** [comment] 2023-12-19 06:26
/triage duplicate
Same as https://github.com/kubernetes/website/issues/44271

**Comment by aj11anuj** [comment] 2024-02-01 13:55
Original issue is now fixed
/close

**Closed by aj11anuj** 2024-02-01 13:55 UTC
Labels: triage/duplicate, language/en, needs-triage
