### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by yongkui** [kubernetes/website#13324] opened 2019-03-21 06:51 UTC
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
After running below command in interactive module 2, got below message
$ kubectl run kubernetes-bootcamp --image=gcr.io/google-samples/kubernetes-bootcamp:v1 --port=8080
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
deployment.apps/kubernetes-bootcamp created

**Proposed Solution:**
Will you consider updating the doc to use the latest command or syntax? since kubectl run seems to be deprecated. Thank you!

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

**Comment by KaranKhirsariya** [comment] 2019-03-30 11:56
Duplicate of #13138

**Comment by sftim** [comment] 2019-06-04 17:31
/close
because this is duplicate issue

**Closed by sftim** 2019-06-04 17:31 UTC
