### ISSUE TITLE
在 Linux 系统中安装并设置 kubectl

### ISSUE THREAD

**Issue by isxiaok** [kubernetes/website#48136] opened 2024-09-30 05:51 UTC
![Uploading wt.png…]()

**Comment by isxiaok** [comment] 2024-09-30 05:54
文档部分，在 Linux 系统中安装并设置页面的用 curl 在 Linux 系统中安装 kubectl中的说明，x86和arm的命令是一样的

**Comment by isxiaok** [comment] 2024-09-30 05:54
文档部分，在 Linux 系统中安装并设置页面的用 curl 在 Linux 系统中安装 kubectl中的说明，x86和arm的命令是一样的

**Comment by dipesh-rawat** [comment] 2024-09-30 08:40
@isxiaok This [description (here)](https://github.com/kubernetes/website/issues/48136#issue-2555628863) doesn't provide enough information to evaluate the issue or determine if any action is needed. Could you please provide more details about the problem you're reporting or the help you need? Please include these details in the issue [description](https://github.com/kubernetes/website/issues/48136#issue-2555628863) in English.

/triage needs-information

**Comment by niranjandarshann** [comment] 2024-10-04 04:06
@isxiaok  You can reopen the issue With Proper description and best practice is to describe the issue in English only putting [zn-ch]  before the description to denote in which localization the issue is . 
For now Marking it as not planned and closing this issue. You can reopen / re raise the issue with proper description.

**Comment by niranjandarshann** [comment] 2024-10-04 04:07
not planned /close  not planned

**Comment by niranjandarshann** [comment] 2024-10-04 04:07
closing this issue marking as not planned
/close

**Closed by niranjandarshann** 2024-10-04 04:08 UTC
Labels: triage/needs-information, needs-triage
