### ISSUE TITLE
Integrate Dark Mode in the Frontend

### ISSUE THREAD

**Issue by barmanroys** [kubernetes/website#46844] opened 2024-06-17 06:52 UTC
**This is a Feature Request**

**What would you like to be added**
Dark Mode, like, for example, the ray documentation. 

**Why is this needed**
Comfort of the eyes, specifically those having chronic migraine. For me personally, every app, website, and IDE I use, are in permanent dark modes. It enables a reader to read longer and more comfortably without straining their eyes.

**Comment by dipesh-rawat** [comment] 2024-06-17 07:51
Looks like duplicate of an issue we already have #25061

/triage duplicate

**Comment by dipesh-rawat** [comment] 2024-06-17 07:52
Also, see #37444

/area web-development

**Comment by sftim** [comment] 2024-06-17 15:26
Help with existing issues https://github.com/kubernetes/website/issues/37444 and #25061 is welcome!

**Comment by sftim** [comment] 2024-06-20 17:26
/close not-planned

This request duplicates existing issues.

**Closed by sftim** 2024-06-20 17:26 UTC
Labels: kind/feature, triage/duplicate, area/web-development, needs-triage
