### ISSUE TITLE
List the supported versions of Kubernetes

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/website#6098] opened 2017-10-30 17:35 UTC
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

The Kubernetes community supports the 3 current minor and previous 2 minor versions of Kubernetes (1.M.P where M is the minor version). This is noted in a design proposal but not elsewhere. This information isn't easily discoverable.

**Proposed Solution:**

List the Kubernetes supported versions where they can be found on the website. The design proposal with the details can be found [here](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew).

**Page to Update:**
_Not yet known. Looking for suggestions._

**Comment by zacharysarah** [comment] 2017-11-06 18:39
@mattfarina 👋 Thanks, good suggestion.

**Comment by mistyhacks** [comment] 2017-12-18 18:57
I think #6442 closes this, right?

**Comment by bacongobbler** [comment] 2017-12-18 20:37
Yes, it does look like #6442 clarifies and closes this issue.

**Comment by tengqm** [comment] 2017-12-19 06:59
Closing this. Please feel free to reopen if it is believed that the issue is not solved yet.

**Closed by tengqm** 2017-12-19 06:59 UTC
Labels: Actionable, good first issue, P2
