### ISSUE TITLE
[hi] localize content/en/docs/concepts/overview/_index.md to Hindi

### ISSUE THREAD

**Issue by kumarankit999** [kubernetes/website#43799] opened 2023-11-03 07:20 UTC
This is a Feature Request

What would you like to be added
Localize content/en/docs/concepts/overview/_index.md to Hindi

Why is this needed
There is no Hindi localization for this file.

Comments

I would like to work on this

/kind feature
/language hi
/sig docs
/assign

**Comment by dipesh-rawat** [comment] 2023-11-03 15:00
/triage duplicate

This looks like a duplicate of issue https://github.com/kubernetes/website/issues/42844

**Comment by aj11anuj** [comment] 2023-11-15 03:25
As it's a proper duplicate of issue #42844 and doesn't adding any value as a separate issue.
/close not-planned

**Closed** 2023-11-15 03:25 UTC
Labels: kind/feature, sig/docs, triage/duplicate, language/hi, needs-triage
