### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by dstaraster** [kubernetes/website#18984] opened 2020-02-05 01:06 UTC
I am unable to complete the Kubernetes "Hello Minikube" tutorial. The command "minikube dashboard" never completes.

Steps to reproduce:

1. Go to https://kubernetes.io/docs/tutorials/hello-minikube/
2. Click the "Launch Terminal" button
3. After minikube has started and there's a command prompt, type "minikube dashboard" and hit Enter

Expected result:
The command returns, and presumably there's a dashboard I can view in a browser.

Actual result:
The command never returns. It gets to "Verifying proxy health..." plus a long URL but doesn't go further. I left it running for more than 10 minutes.

OS: MacOS 10.14.6, Windows 10
Browsers: Chrome 80.0.3987.87, Edge

**Comment by Colstuwjx** [comment] 2020-02-05 05:20
I checked this page, and I didn't see the result you said, instead, I met issue like [this](https://github.com/kubernetes/website/issues/12968#issuecomment-570227566), the `minikube dashboard` did open a proxy url, but I could NOT visit the page via katacoda.

I'm not sure what's the root cause for your case, but I think this part should be problematic.

/language en
/kind bug

**Comment by paleboot** [comment] 2020-02-07 09:11
Confirmed bug, persisted for more than 30 minutes. Both browser shows `500 Internal Server Error` error code in each respective console:
![chromeConsoleKubernetesTutorial](https://user-images.githubusercontent.com/54321501/74016075-68ddb780-49c4-11ea-836d-cfe129704b90.png)
![firefoxConsoleKubernetesTutorial](https://user-images.githubusercontent.com/54321501/74016081-6aa77b00-49c4-11ea-8f02-dad8b0707d05.png)



OS: Pop!_OS 19.10 
Browsers: Chrome Version 80.0.3987.87 (Official Build) (64-bit) & Mozilla Firefox 72.0.2 (64-bit)

**Comment by BenHall** [comment] 2020-02-17 20:09
Sorry for the late reply. We are working on a fix due to a timing issue.

**Comment by RA489** [comment] 2020-03-03 09:09
You can also emit the URL using `minikube dashboard --url`

**Comment by tengqm** [comment] 2020-07-11 07:38
There have been no further complaints about the katacoda.
I'm closing this now, but pls feel free to reopen if the problem persists.
/close

**Closed** 2020-07-11 07:38 UTC
Labels: kind/bug, language/en, lifecycle/rotten
