### ISSUE TITLE
Trouble previewing website locally on Windows

### ISSUE THREAD

**Issue by wjkhappy14** [kubernetes/website#36937] opened 2022-09-21 06:43 UTC
**This is a Bug Report**

**Problem:**
![image](https://user-images.githubusercontent.com/1332924/191432710-c2bd6c89-b1b8-46bd-99d4-9759f191b6f7.png)

**Proposed Solution:**
when run   **make container-serve**  on windows 10
then got :loading translations: "/src/i18n/de.toml:1:1": failed to load translations: toml: invalid character at start of key: .

**Page to Update:**
https://kubernetes.io/...

**Comment by jihoon-seo** [comment] 2022-09-21 07:39
Maybe-relevant issue:
- #28910

**Comment by wjkhappy14** [comment] 2022-09-21 09:46
first delete the i18n dir
then run  mklink /J "E:\source\code\k8s-website\i18n" "E:\source\code\k8s-website\data\i18n"

**Comment by sftim** [comment] 2022-09-23 08:38
This is a Windows issue (and is almost a duplicate of #28910)

/retitle Trouble previewing website locally on Windows

**Comment by Kanika637** [comment] 2023-03-16 18:22
I want to work on this issue.
/assign

**Closed** 2023-10-09 13:26 UTC
Labels: kind/bug, triage/accepted
