### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/update/update-intro/

### ISSUE THREAD

**Issue by rshrimp** [kubernetes/website#14882] opened 2019-06-13 21:04 UTC
**This is a Bug Report**

**Problem:**carousel feature of going through the diagrams is not working on safari/chrome browsers

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment] 2019-06-14 08:45
Thanks for the report. It doesn't work on firefox either.
/language en

This is also a duplicate of issue #14809 
/triage duplicate

**Closed** 2019-06-16 09:34 UTC
Labels: language/en, triage/duplicate
