### ISSUE TITLE
Trouble following guide #Install and Set Up kubectl on Linux (on CentOS)

### ISSUE THREAD

**Issue by shaquiba739** [kubernetes/website#32732] opened 2022-04-02 23:14 UTC
We are unable to install the kubectl tool in centos 7 as getting the below error.

Cuurent configuration of repo
![image](https://user-images.githubusercontent.com/61896157/161404392-3fc27f6a-24dc-466e-897b-98f4aac29619.png)

The error we are getting while trying to download the kubectl.
![image](https://user-images.githubusercontent.com/61896157/161404452-27d03be1-0dfa-4c06-a26c-beb6359da906.png)

**Comment by sftim** [comment] 2022-04-03 18:26
/retitle Trouble following guide #Install and Set Up kubectl on Linux (on CentOS)
Duplicate of #32207
/triage duplicate
/language en

**Comment by sftim** [comment] 2022-06-25 22:17
/close

Original issue fixed in https://github.com/kubernetes/website/pull/34546

**Closed** 2022-06-25 22:17 UTC
Labels: triage/duplicate, language/en, needs-triage
