### ISSUE TITLE
Issue with k8s.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/

### ISSUE THREAD

**Issue by bgranier** [kubernetes/website#38427] opened 2022-12-12 14:47 UTC
Hi,

In my case the two maven module can not be built so it is not possible to follow the tutorial ....

**Comment by utkarsh-singh1** [comment] 2022-12-12 16:29
Hi @bgranier, can you post the full error here as it can be fully understandable?

Related doc - https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/

/language en
/priority awaiting-more-evidence

**Comment by bgranier** [comment] 2022-12-12 16:52
Hi, 

With pleasure (french idioms) here is the trace 👍 
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.10:build (default) on project system: Could not build image: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by sftim** [comment] 2022-12-12 16:59
This is a duplicate of issue https://github.com/kubernetes/website/issues/37994

/triage duplicate
/remove-priority awaiting-more-evidence

**Comment by mehabhalodiya** [comment] 2022-12-22 04:13
Per [this comment](https://github.com/kubernetes/website/issues/38427#issuecomment-1346880160), I am closing this issue. Thanks!

/close

**Closed by mehabhalodiya** 2022-12-22 04:13 UTC
Labels: triage/duplicate, language/en, needs-triage
