### ISSUE TITLE
Interactive Tutorial - Updating Your App

### ISSUE THREAD

**Issue by humbienri** [kubernetes/website#34825] opened 2022-07-05 13:52 UTC
I've not been able to get the actual Terminal to load at all. Been trying over the whole weekend with no success so not able to actually follow the tutorial. Can't type (or "click enter") to enter the kubectl commands.

**Comment by jihoon-seo** [comment] 2022-07-06 04:58
Page: https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-interactive/
/label team/katacoda

@humbienri have you tried disabling the ad blocker you are using and then reloading?

**Comment by herodriguez7** [comment] 2022-07-06 14:32
@jihoon-seo I've done that and it worked! Thank you. I am able to follow along with the tutorial. I do wonder though...how come my ad blocker is picking it up as an "Ad"?

Also, why is it that the first 4 modules did not have this problem? Do you know?

Now I am curious to try it on Chrome with whatever Ad Blocker I have there to see if that too trips things up.

Thanks again @jihoon-seo!

**Comment by shannonxtreme** [comment] 2022-07-07 12:16
Since the issue is resolved, should we close?

**Comment by herodriguez7** [comment] 2022-07-07 14:47
I thought about closing the issue but could not find a button. But then I had those lingering questions. If you could answer them, please?

**Comment by jihoon-seo** [comment] 2022-08-17 22:16
@herodriguez7 
> how come my ad blocker is picking it up as an "Ad"?

Please refer this issue: #32832

> Also, why is it that the first 4 modules did not have this problem? Do you know?

I am sorry to say that I don't know.

@herodriguez7 Since the issue is resolved, let me close this issue. 😊
/close

**Closed** 2022-08-17 22:17 UTC
Labels: team/katacoda, needs-triage
