### ISSUE TITLE
Run a Replicated Stateful Application

### ISSUE THREAD

**Issue by dc-weizhenhua** [kubernetes/website#35544] opened 2022-07-29 13:29 UTC
1、there is no `hostname` command in mysql:5.7;

**Comment by jihoon-seo** [comment] 2022-07-30 07:49
It seems that this issue is a duplicate of #35432.

**Comment by dc-weizhenhua** [comment] 2022-07-30 09:05
> It seems that this issue is a duplicate of #35432.

#35432.  is still open!  I  thought it's so obvious error，where there's no solution stiill!

**Comment by tengqm** [comment] 2022-08-01 03:30
/close
Closing as a dup.

**Closed** 2022-08-01 03:30 UTC
Labels: needs-triage
