### ISSUE TITLE
[hi] Localize concepts/overview/components.md/ into Hindi

### ISSUE THREAD

**Issue by ShivangShandilya** [kubernetes/website#39107] opened 2023-01-25 21:02 UTC
The components.md file needs to be translated into Hindi for the people who understand the language.
Link: https://kubernetes.io/docs/concepts/overview/components/

**Comment by vaibhav2107** [comment] 2023-01-26 10:20
This issue is already opened in #35063 and a PR #38699 has also been raised for this issue

**Comment by ShivangShandilya** [comment] 2023-01-26 10:31
then can I work on Kubernetes-api.md, if it's not addressed till now. I can edit this very same issue instead of opening a new one, can you please tell me if that issue is open or not? 
Regards @vaibhav2107

**Comment by kundan2707** [comment] 2023-01-27 08:09
/triage duplicate
This is duplicate of #35063

**Closed** 2023-01-27 12:46 UTC
Labels: kind/feature, triage/duplicate, needs-triage
