### ISSUE TITLE
Using kubectl to Create a Deployment

### ISSUE THREAD

**Issue by weixinyou** [kubernetes/website#46734] opened 2024-06-07 19:23 UTC
The image does not support arm system

**Comment by T-Lakshmi** [comment] 2024-06-07 19:28
/language en
page: https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

**Comment by stmcginnis** [comment] 2024-06-07 19:36
Thanks for reporting this, but this is a duplicate of https://github.com/kubernetes/website/issues/45420 and falls under the umbrella effort being tracked with https://github.com/kubernetes/website/issues/45822.

If you can help there, contributions are very welcome. If you would just like to track it, you can subscribe to get notifications for any updates to #45822.

/close

**Closed by stmcginnis** 2024-06-07 19:37 UTC
Labels: language/en, needs-triage
