### ISSUE TITLE
Container ports in https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/ 

### ISSUE THREAD

**Issue by rhpereda** [kubernetes/website#19812] opened 2020-03-23 19:05 UTC
I'm new in kubernetes and i'm trying to learn by doing the tutorials posted on the official documentation. In the module: https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/ we created a deployment and successfuly complete all the tasks. In the next module (https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/ ) apparently takes the previous step to work from there, but the command curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/proxy/ needs to have a port mapping from the container and as this moment, there is nothing in the tutorial related to that. I'm trying to do all the tasks using minikube on my local machine and at this point i'm getting: Error trying to reach service: 'dial tcp 172.17.0.4:80: connect: connection refused'. Something is missing from the lessons....
Any helpm would be appreciated ...
thanks in advance..

**Comment by namaggarwal** [comment] 2020-04-05 14:19
Duplicate of #18079 There is a solution there

**Comment by tengqm** [comment] 2020-06-14 13:08
/close
as a dup

**Closed** 2020-06-14 13:09 UTC
