### ISSUE TITLE
Installing kubeadm

### ISSUE THREAD

**Issue by mikejoh** [kubernetes/website#39707] opened 2023-02-27 17:32 UTC
In this [part](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl) of the docs the install fails on Debian based systems since the key URL returns a 500 (hosted by Google), with this PR https://github.com/kubernetes/k8s.io/pull/4837 and using the work-around URL from this comment: https://github.com/kubernetes/k8s.io/pull/4837#issuecomment-1446426585 it now works. 

Shall we change the URL in the docs?

**Comment by dipesh-rawat** [comment] 2023-02-27 17:59
@mikejoh  See work around with new URL here: https://github.com/kubernetes/k8s.io/pull/4837#issuecomment-1446426585

**Comment by dipesh-rawat** [comment] 2023-02-27 17:59
Duplicate of https://github.com/kubernetes/kubernetes/issues/116096
/triage duplicate

**Closed** 2023-02-27 18:04 UTC
Labels: triage/duplicate, needs-triage

**Comment by mikejoh** [comment] 2023-02-27 18:06
Closing in favor of, as mentioned, https://github.com/kubernetes/kubernetes/issues/116096!
