### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by marcel-st** [kubernetes/website#20281] opened 2020-04-13 09:49 UTC
Hi Guys,

the Interactive Terminal says it's out of diskspace, someone with admin privileges might need to have look at the backend.

Cheers,

Marcel

**Comment by sftim** [comment] 2020-04-13 10:35
@BenHall you might want to know about this
/kind bug
/priority important-soon

**Comment by tengqm** [comment] 2020-06-14 06:38
The problem is still there? @marcel-st

**Comment by BenHall** [comment] 2020-06-16 08:38
On the Katacoda side we adjusted our infrastructure so this shouldn't happen in future.

**Comment by sftim** [comment] 2020-06-16 08:41
@BenHall based on what you've written I'll close this.
@marcel-st please feel free to reopen the issue if symptoms recur

**Comment by irvifa** [comment] 2020-10-17 15:05
/ close

**Closed** 2020-11-16 15:19 UTC
Labels: kind/bug, lifecycle/rotten, priority/important-soon
