### ISSUE TITLE
"Drain the node" should be prior to Call "kubeadm upgrade" to ensure safe upgrade

### ISSUE THREAD

**Issue by nidhi-singh02** [kubernetes/website#39539] opened 2023-02-19 13:12 UTC
**This is a Bug Report**

**Problem:* In the documentation for upgrading cluster via kubeadm for Upgrading control plane nodes https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#upgrading-control-plane-nodes, the order of steps seems not appropriate.
 *

**Proposed Solution:**
The order os steps should be 
**Page to Update:**
https://kubernetes.io/...

**Comment by neolit123** [comment] 2023-02-20 09:59
/close
duplicate of https://github.com/kubernetes/website/issues/39540
?

**Closed** 2023-02-20 10:02 UTC
Labels: kind/bug, needs-triage
