### ISSUE TITLE
Interactive Tutorial - Creating a Cluster

### ISSUE THREAD

**Issue by mahyarevafa** [kubernetes/website#37711] opened 2022-11-04 10:07 UTC
Hello. I use a laptop with 14" screen for kubernetes tutorial. but "The screen is too narrow to interact with the Terminal, please use a desktop/tablet." error is displayed. what's wrong?

**Comment by sftim** [comment] 2022-11-04 15:15
Thank you for spotting this.

This issue is a duplicate of issue https://github.com/kubernetes/website/issues/37431

/triage duplicate

**Comment by utkarsh-singh1** [comment] 2022-11-23 10:00
Facing same issue with 14" laptop, but it does not affect the interactive tutorial 

>![Screenshot_20221123_152730](https://user-images.githubusercontent.com/96516301/203518506-cc5e8f8c-83b4-4a35-8cef-cfaed76ea95a.png)

**Comment by tengqm** [comment] 2023-02-18 11:22
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).

**Closed by tengqm** 2023-02-18 11:22 UTC
Labels: triage/duplicate, needs-triage
