### ISSUE TITLE
Issue with k8s.io/releases/

### ISSUE THREAD

**Issue by JohnTangZX** [kubernetes/website#47601] opened 2024-08-21 02:00 UTC
The schedule link for 1.32 reports 404.

Upcoming Release
Check out the [schedule](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.32) for the upcoming 1.32 Kubernetes release!

https://github.com/kubernetes/sig-release/tree/master/releases/release-1.32

**Comment by Shubham82** [comment] 2024-08-21 10:29
Page: https://kubernetes.io/releases/#upcoming-release

@JohnTangZX, The corresponding PR is not merged yet in the kubernetes/sig-release repository, once it is merged, the information will be there.
https://github.com/kubernetes/sig-release/pull/2604

**Comment by sftim** [comment] 2024-08-21 11:44
/sig release

Not a bug in k/website; the link is correct and https://github.com/kubernetes/sig-release/pull/2604 will make it come about.

@JohnTangZX thanks for reporting this. I could transfer this issue to SIG Release, or close it, or leave it open but with no action needed by this SIG.

What do you prefer?

**Comment by tengqm** [comment] 2024-08-25 00:58
/close
Feel free to reopen if the link fails while it should work.

**Closed by tengqm** 2024-08-25 00:58 UTC
Labels: sig/release, needs-triage
