### ISSUE TITLE
Blank lines when copying example manifests

### ISSUE THREAD

**Issue by umeshw77** [kubernetes/website#37206] opened 2022-10-08 07:26 UTC
I have a suggestion for the "copy to clipboard" option that is available at the right top of any YAML file examples in docs. The copied content when pasted on any editor seems to insert newlines, whereas if same yaml if copied manually by selecting text doesn't insert newlines. The newlines makes the content pretty much unreadable, can this be addressed please?

e.g. Text copied using copy to clipboard option:
apiVersion: v1

kind: Pod

metadata:

  name: userns

spec:

  hostUsers: false

  containers:

  - name: shell

    command: ["sleep", "infinity"]

    image: debian
-----

Below is manually copied YAML:
apiVersion: v1
kind: Pod
metadata:
  name: userns
spec:
  hostUsers: false
  containers:
  - name: shell
    command: ["sleep", "infinity"]
    image: debian

**Comment by sftim** [comment] 2022-10-08 19:43
Similar to:
#36003
#36361
#36813
#37088

/triage duplicate
/retitle Blank lines when copying example manifests

**Comment by jihoon-seo** [comment] 2022-11-30 02:35
This issue is a duplicate of #34447.

**Closed** 2023-04-29 04:10 UTC
Labels: lifecycle/rotten, triage/duplicate, needs-triage
