### ISSUE TITLE
Avoid using the words "master" and "slave"

### ISSUE THREAD

**Issue by ecmonsen** [kubernetes/website#30675] opened 2021-11-29 20:31 UTC
Please change the example code to avoid references to slavery. Example page containing such references: https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/

There are many news articles about this if you want to know more. Here is one.

https://www.forbes.com/sites/elanagross/2020/07/03/twitter-and-jpmorgan-chase-are-the-latest-companies-to-remove-terms-master-and-slave-from-programming-code/?sh=244419d63ced

**Comment by sftim** [comment] 2021-11-29 23:55
@ecmonsen this is a duplicate of issue #21621. You're welcome to open pull requests to help with the cleanup.

/triage duplicate

**Comment by ecmonsen** [comment] 2021-11-30 18:52
Thank you, I should have checked existing issues!

**Comment by sftim** [comment] 2021-12-03 00:45
/close
Duplicates #21621

**Closed by sftim** 2021-12-03 00:45 UTC
Labels: triage/duplicate, language/en
