### ISSUE TITLE
Partial text on the navigation bar

### ISSUE THREAD

**Issue by Affan-7** [kubernetes/website#42241] opened 2023-07-27 06:02 UTC
**This is a Feature Request**

**What would you like to be added**
Make the navigation bar horizontally re-sizeable.

**Why is this needed**
I can't see the navigation index entirely unless I zoom out on my page.
![Screenshot from 2023-07-27 11-28-06](https://github.com/kubernetes/website/assets/72978371/1a6db38d-34ac-4ffd-9dac-1afd318c8e5d)

**Comment by T-Lakshmi** [comment] 2023-07-27 06:56
related issue #38663

**Comment by dipesh-rawat** [comment] 2023-07-27 08:58
Looks like a duplicate of issue https://github.com/kubernetes/website/issues/39621
Currently, there is PR https://github.com/kubernetes/website/pull/41695 opened which attempts to fix this issue.

/triage duplicate

**Comment by Ritikaa96** [comment] 2023-09-20 04:08
#41695 is merged now.
/close
in favor of the PR: #41695

**Closed by Ritikaa96** 2023-09-20 04:08 UTC
Labels: kind/feature, triage/duplicate, area/web-development, needs-triage
