### ISSUE TITLE
Menu in reverse order

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/website#8702] opened 2018-05-23 17:41 UTC
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
A menu is in reverse order. In the image below see Annotations. That list is in reverse order. Annotations should be at the bottom.

![screen shot 2018-05-23 at 1 37 22 pm](https://user-images.githubusercontent.com/62991/40441360-cebb425c-5e8e-11e8-84ca-c4a1751f1084.png)

**Comment by tfogo** [comment] 2018-05-24 00:26
Specifically it looks like all sub-lists in the TOC are in alphabetical order.

**Comment by Bradamant3** [comment] 2018-05-24 14:08
Yes, alphabetical order is the default in Hugo. We have to go in and manually assign weights to individual pages to customize the order. It's on a TODO list; thanks for filing the issue.

**Comment by steveperry-53** [comment] 2018-06-01 04:57
Duplicate of #8239.

**Closed by steveperry-53** 2018-06-01 04:57 UTC
