### ISSUE TITLE
???

### ISSUE THREAD

**Issue by Raen123** [kubernetes/website#45966] opened 2024-04-22 13:43 UTC
> ```html
> <a href="https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/45866/#/?version=2"><img src="https://s3.amazonaws.com/cla-project-logo-prod/cla-not-signed.svg" alt="CLA Not Signed" align="left" height="28" width="328"></a><br/><br /><ul><li><a href='https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/45866/#/?version=2' target='_blank'>:x:</a> - login: @Raen123 . The commit (e770f20f8b4fa726799560cc6011ef7fc3b95131) is not authorized under a signed CLA. <a href='https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/45866/#/?version=2' target='_blank'>Please click here to be authorized</a>. For further assistance with EasyCLA, <a href='https://jira.linuxfoundation.org/servicedesk/customer/portal/4' target='_blank'>please submit a support request ticket</a>.</li></ul>
> ```

_Originally posted by @linux-foundation-easycla[bot] in https://github.com/kubernetes/website/issues/45866#issuecomment-2053864717_

**Comment by thisisharrsh** [comment] 2024-04-22 14:01
Hi @Raen123, Could you please explain the issue you are facing. 
/triage needs-information

**Comment by sftim** [comment] 2024-04-22 14:49
Maybe https://github.com/kubernetes/website/pull/45866#issuecomment-2069742169 will help?

**Comment by divya-mohan0209** [comment] 2024-04-28 07:48
Hello @Raen123, would request that you raise issues/PRs with appropriate description. Without understanding what the issue is, we'll be unable to help you out any further. 
Closing this issue since the user has repeatedly been opening issues and PRs with no context and has not been responsive over them.
/close

**Closed by divya-mohan0209** 2024-04-28 07:48 UTC
Labels: triage/needs-information, language/en, needs-triage
