### ISSUE TITLE
Dark/Light Mode Feature Request and Logo for both mode

### ISSUE THREAD

**Issue by Ayush9026** [kubernetes/website#44159] opened 2023-11-30 11:38 UTC
**This is a Feature Request**

I would like to propose the addition of a dark/light mode toggle feature to enhance the user experience on the website. Marked in screenshot below.

![Kubernetes website front page](https://github.com/kubernetes/website/assets/114745463/86dcfb45-4c54-437c-9177-a811acfcca58)

**What would you like to be added**
Feature Details:

**Toggle Button**: Implement a toggle button in the header or settings section that allows users to switch between dark and light modes.
**Persistent Preference**: Make the selected mode persist across sessions using local storage or a similar mechanism.

**Why is this needed**
Dark mode is becoming a standard feature in many websites and applications due to its potential benefits for eye strain reduction and improved visibility in low-light environments. Providing users with the option to choose their preferred mode can enhance the overall usability of the website.

**Comment by sftim** [comment] 2023-11-30 12:13
/retitle Dark/Light Mode Feature Request and Logo for both mode
/triage duplicate

**Comment by sftim** [comment] 2023-11-30 12:13
Thanks.

See the original issue for further discussion; this is a near-exact duplicate of it.

/close not-planned

**Closed** 2023-11-30 12:13 UTC
Labels: kind/feature, triage/duplicate, needs-triage
