### ISSUE TITLE
 link "worker node running Windows Server" pointing to wrong documentation

### ISSUE THREAD

**Issue by KRISHNA-VKS** [kubernetes/website#35050] opened 2022-07-15 09:55 UTC
when the link is clicked "[worker node running Windows Server](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/)" is moving towards a wrong location as the above location content is not available. Its switching to https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/ location.

**Comment by neolit123** [comment] 2022-07-15 11:17
Duplicate of
https://github.com/kubernetes/website/issues/34476

/close

**Closed** 2022-07-15 11:18 UTC
Labels: needs-triage
