### ISSUE TITLE
Broken links in main documentation page

### ISSUE THREAD

**Issue by drexpp** [kubernetes/website#10917] opened 2018-11-07 14:52 UTC
**This is a...** 
- [ ] Feature Request
- [X] Bug Report

**Problem:**
 
Broken links related to the url _"docs/home/**community/**"_, resolves into a 404 error.

Known broken links:
- https://kubernetes.io/docs/community/keps/
- https://kubernetes.io/docs/community/guide/
- https://kubernetes.io/docs/community/devel/
- https://kubernetes.io/docs/community/mentoring/

**Proposed Solution:**

I tried to find where the problem could be located but sadly I wasn't able to easy spot where it is. I would be willing to help if I could get some guidance. Otherwise someone more experienced could resolve it.

**Page to Update:**

Links related to https://kubernetes.io/docs/home/community

**Steps to reproduce**

1. Navigate to main page https://kubernetes.io/ click on "Documentation" (Top bar).
2. We should be in https://kubernetes.io/docs/home/ .There are three buttons that should appear "Users, contributors and browse docs". 

    - The button "Users" does not contain any broken links.

    -  The option "Contributors" does contain broken links inside the boxes with title "I want to..." located in  "Contributors/Code Contributor/Foundational" and "Contributors/Code Contributor/Intermediate".

    - The other 2 found broken links are located in "Contributors/Community contributor/Foundational"

**Comment by charrywanganthony** [comment] 2018-11-11 15:17
This was intentional  https://github.com/kubernetes/website/pull/10589#issuecomment-429966662

**Comment by DanyC97** [comment] 2019-03-28 10:48
/language en
@charrywanganthony if this was intentional, am i right assuming is safe to close it ?

**Comment by thecrudge** [comment] 2019-04-24 17:04
This can be /close

Unable to reproduce @DanyC97 @jimangel @zacharysarah

**Comment by DanyC97** [comment] 2019-04-25 08:39
/close

thank you @thecrudge for providing feedback

**Closed by DanyC97** 2019-04-25 08:39 UTC
Labels: language/en, lifecycle/rotten
