### ISSUE TITLE
Documentation issue: Upgrading kubeadm clusters

### ISSUE THREAD

**Issue by aurelienlegrand** [kubernetes/website#29725] opened 2021-09-16 10:17 UTC
I think I spotted a documentation issue.

On this page: https://v1-20.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

The link "Upgrading a kubeadm cluster from 1.19 to 1.20" gives you instructions on how to upgrade from version 1.21.x to version 1.22.x, not from version 1.19.x to 1.20.x.

**Comment by neolit123** [comment] 2021-09-16 11:39
Duplicate of
https://github.com/kubernetes/website/issues/27525

Unfortunately the required fix still needs review.

/close

**Closed** 2021-09-16 11:40 UTC
Labels: needs-triage
