### ISSUE TITLE
Retain LGTM through squashes

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#24043] opened 2020-09-22 11:44 UTC
**This is a Feature Request**

**What would you like to be added**
Configure Prow to retain LGTM when a PR is squashed.

**Why is this needed**
If someone reviews a PR and marks it LGTM, it's frustrating if a later squash (that makes no code changes) cancels the review. It means extra work for the reviewer that could be cut out.

**Comments**
https://github.com/kubernetes/test-infra/issues/19147#issuecomment-693006340 describes how to configure this. It might already be set up; in that case, it's OK to note that and close this issue.

**Comment by kbhawkey** [comment] 2020-09-22 13:07
I think this makes sense as long as the squashing does not involve further changes.

**Comment by habibrosyad** [comment] 2020-09-22 13:50
I think could help with this one, the result could be verified once the config is merged and up.

/assign

**Closed** 2020-09-23 23:14 UTC

**Comment by habibrosyad** [comment] 2020-09-24 08:05
Looks like the new config has kicked in https://github.com/kubernetes/website/pull/24088#issuecomment-698182440

**Comment by habibrosyad** [comment] 2020-09-24 08:07
Looks like the new config is up, e.g. https://github.com/kubernetes/website/pull/24088#issuecomment-698182440, need to verify whether the lgtm will survive through squash.

**Comment by habibrosyad** [comment] 2020-09-24 09:43
Confirmed that the setting working correctly https://github.com/kubernetes/website/pull/24096...
