### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-intro/

### ISSUE THREAD

**Issue by pdtoal** [kubernetes/website#8558] opened 2018-05-15 22:31 UTC
**This is a...** 

- [ ] Feature Request
- [X ] Bug Report

**Problem:**
Link to Kubernetes-Basic GitHub repository shows a 404.

**Proposed Solution:**

**Page to Update:**
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-intro/

**Comment by ajaeger** [comment] 2018-05-16 07:04
/triage duplicate

Duplicate of #8547

**Comment by shubheksha** [comment] 2018-09-22 16:01
Closing this as it's a duplicate.
/close

**Closed by shubheksha** 2018-09-22 16:01 UTC
Labels: lifecycle/rotten, triage/duplicate
