### ISSUE TITLE
Search within page in browser showing content not visible on screen

### ISSUE THREAD

**Issue by DevangCoder** [kubernetes/website#45484] opened 2024-03-09 18:26 UTC
When trying to search on the page, for unsuccessful search, it still shows the keyword from its subsections that are not open.
for example When I search for the keyword "pod" on the page, it shows that result value > 0 however there is no keyword present on the page.
![image](https://github.com/kubernetes/website/assets/51353816/961d4bc0-53d4-440e-b6dd-4abce8c7d9b2)

**Comment by dipesh-rawat** [comment] 2024-03-10 00:29
/retitle Search within page in browser showing content not visible on screen
/area web-development

**Comment by dipesh-rawat** [comment] 2024-03-10 00:30
This appears to be a duplicate of existing issue https://github.com/kubernetes/website/issues/41469
/triage duplicate

**Comment by sftim** [comment] 2024-03-10 18:34
Yes, this is a duplicate. Would you be willing to close this @DevangCoder ?

Issues only get fixed once someone volunteers time to work on them.

**Closed** 2024-03-10 18:35 UTC
Labels: triage/duplicate, area/web-development, needs-triage
