### ISSUE TITLE
Issue with k8s.io/docs/concepts/api-extension/custom-resources/

### ISSUE THREAD

**Issue by neopaf** [kubernetes/website#8392] opened 2018-05-07 08:46 UTC
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

"Advanced features and flexibility" chapter table is broken

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by praseodym** [comment] 2018-05-07 21:55
I think this is a duplicate of #8271.

**Closed** 2018-05-10 17:31 UTC
Labels: Actionable, P2, good first issue

**Comment by neopaf** [comment] 2018-05-11 12:12
thumbs up!
