### ISSUE TITLE
Connection refused error when using curl with minikube IP and Node Port in "Performing a Rolling Update" tutorial

### ISSUE THREAD

**Issue by emmankip** [kubernetes/website#42939] opened 2023-09-07 16:28 UTC
command: curl http://"$(minikube ip):$NODE_PORT" connection refused

**Comment by dipesh-rawat** [comment] 2023-09-07 17:00
/retitle Connection refused error when using curl with minikube IP and Node Port in "Performing a Rolling Update" tutorial

**Comment by dipesh-rawat** [comment] 2023-09-07 17:00
This looks like duplicate of #42938 
/triage duplicate

**Comment by Ritikaa96** [comment] 2023-09-20 04:04
/close
closing in favor of #42938 
as both address same issue.

**Closed** 2023-09-20 04:04 UTC
Labels: triage/duplicate, language/en, needs-triage
