### ISSUE TITLE
The picture and description should be changed.

### ISSUE THREAD

**Issue by 911432** [kubernetes/website#45221] opened 2024-02-19 22:29 UTC
https://github.com/kubernetes/website/issues/40554#issuecomment-1952867883

> - A cluster is made up of one or more nodes
> - If a node has control plane services on it, it is usually referred to as a control plane node
> - If a node is meant for running workloads (sometimes called apps) then it is a worker node
> - Usually a control plane node is tainted so it can be dedicated to performing control plane activities, but that isn't a strict requirement and a node could be functioning as both a control plane and worker

According to this [figure and description](https://github.com/kubernetes/website/blob/release-1.28/content/en/docs/concepts/overview/components.md), the cluster appears to have nodes and control planes.
I think there should be a node in the lower part of the cluster and there should be a control plane and a worker node in the lower part of the node.

**Comment by tamilselvan1102** [comment] 2024-02-20 04:43
Page related to the issue: https://kubernetes.io/docs/concepts/overview/components/

**Comment by sftim** [comment] 2024-02-20 09:53
/priority awaiting-more-evidence

> a worker node in the lower part of the node

This doesn't match my understanding of how Kubernetes works.

**Comment by 911432** [comment] 2024-02-20 12:59
@sftim
- If a node is meant for running workloads (sometimes called apps) then it is a worker node

As I know, there is a worker machine called a node, which has a pod set.
According to this [document](https://kubernetes.io/docs/concepts/workloads/), I understand that there is a pod and the application is working due to one or more pods.
I understand that the node where the application operates is called a worker node.

**Comment by stmcginnis** [comment] 2024-02-20 13:54
I also do not see what the issue is with the referenced page. 

> the cluster appears to have nodes and control planes.

This is comparing two different concepts, so I'm a bit confused by what you are trying to say. Can you restate the issue in another way maybe?

Maybe just a typo, but you say a plural "control planes" - there is only one control plane. There is one control plane. One or  more nodes. Those nodes are usually classified by what type of role they are performing in the cluster. Sometimes it is to run some of the control plane services. If that is the node's primary purpose, then it is typically referred to as a "control plane node." Sometime it is dedicated for just running your workloads, where it is typically called a "worker node." I say typically, because these are just names that are commonly used to refer to them. They are still just nodes in the cluster.

You can also have the control plane being provided elsewhere, where there isn't an associated node. If you looks at EKS, GKE, [Kamaji](https://kamaji.clastix.io/getting-started/), etc., those services are fully managed and the control plane is run "hidden" where there are not cluster nodes dedicated to running those control plane services. 

So the referenced doc is accurate that a node is [something that runs kubelet and kube-proxy](https://kubernetes.io/docs/concepts/overview/components/#node-components). It may or may not also run other things, but that is just a matter of how someone chooses to set up their cluster and where they want to run the services that provide the control plane, whether they want to dedicate nodes to providing those services, etc.

**Comment by 911432** [comment] 2024-02-20 14:29
@stmcginnis 
A cluster is a set of nodes; some nodes act as control planes; others act as workloads.
Of course, one node can act as a control plane and workload.
However, with this document, the cluster appears to consist of a control plane and nodes.

**Comment by 911432** [comment] 2024-02-20 14:29
@stmcginnis 
A cluster is a set of nodes; some nodes act as control planes; others act as workloads.
Of course, one node can act as a control plane and workload.
However, with this [document](https://github.com/kubernetes/website/blob/release-1.28/content/en/docs/concepts/overview/components.md), the cluster appears to consist of a control plane and nodes.

**Comment by stmcginnis** [comment] 2024-02-20 14:46
> cluster appears to consist of a control plane and nodes

Again, this is combining two different concepts, so I'm not really sure what you mean.

> some nodes act as control planes

No multiple control planes. There is a control plane, singular. That control plane may be services by one or more nodes. Nodes are members of the cluster and may be dedicated for specific things, or may be general purpose and fulfill multiple roles.

**Comment by 911432** [comment] 2024-02-20 22:55
@stmcginnis

- Again, this is combining two different concepts, so I'm not really sure what you mean.

In [this figure](https://kubernetes.io/images/docs/components-of-kubernetes.svg) and [document](https://kubernetes.io/docs/concepts/overview/components/), the components of the cluster look like control plane and node.

- some nodes act as control planes

Control plane is singular.
However, The control plane operates on one or more nodes.

**Comment by 911432** [comment] 2024-02-20 22:57
@stmcginnis

- Again, this is combining two different concepts, so I'm not really sure what you mean.

In [this figure](https://kubernetes.io/images/docs/components-of-kubernetes.svg) and [document](https://kubernetes.io/docs/concepts/overview/components/), the components of the cluster look like control plane and node.

- some nodes act as control planes

Control plane is singular.
However, The control plane operates on one or more nodes.
These contents are difficult to understand in the document.

**Comment by sftim** [comment] 2024-02-20 23:17
Whilst I get that you don't understand the page, the feedback isn't really actionable @911432.

If you can explain the questions you have or point out where the page isn't clear, we can try to fix that. If you explain your misunderstandings, no matter what level of detail, we're less enlightened. The people who'll fix the issue already know how Kubernetes actually works; what we need to learn is how come the diagram doesn't make that clear to a novice.

**Comment by stmcginnis** [comment] 2024-02-21 00:04
1. You don't know, and don't need to know. The control plane may be on nodes, it may be a service running as its own process, it may be a service running elsewhere in the environment. The point of the picture is to show that there is a control plane, not the technical details of how it's being operated.
2. Add application pods in the referenced diagram would make it much too busy, and I think would add confusion. The diagram is trying to show the components that make up kubernetes, not what you are using kiubernetes to do.
3. Yes, there is a control plane, and there are nodes. As it shows, the nodes would be running kubelet, and usually kube-proxy. Nodes may or may not be running other things, but that is irrelevant to what the diagram is trying to show.

**Comment by 911432** [comment] 2024-02-21 00:27
1. Due to the corresponding diagrams and descriptions, it seems wrong to be a [control plane node](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/).
According to the overview's [document](https://kubernetes.io/docs/concepts/overview/components/), k8s have clusters and are divided into control planes and nodes within clusters, but this is not true.
2. A document on the same page in the diagram describes a worker node, but when you look at the diagram, I don't know what a worker node is.

**Comment by 911432** [comment] 2024-02-21 00:28
1. Due to the corresponding diagrams and descriptions, it seems wrong to be a [control plane node](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/).
According to the overview's [document](https://kubernetes.io/docs/concepts/overview/components/), k8s have clusters and are divided into control planes and nodes within clusters, but this is not true.
2. A document on the same page in the diagram describes a worker node, but Looking at the diagram, I don't know what a worker node is.

**Comment by 911432** [comment] 2024-02-21 00:34
1. Due to the corresponding diagrams and descriptions, it seems wrong to be a [control plane node](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/).
According to the overview's [document](https://kubernetes.io/docs/concepts/overview/components/), k8s have clusters and are divided into control planes and nodes within clusters, but this is not true.
2. A document on the same page in the diagram describes a worker node, but Looking at the diagram, I don't know what a worker node is.

So, the components
cluster
node
control plane node / worker node
I think to divide it like this.

**Comment by 911432** [comment] 2024-02-21 00:35
1. Due to the corresponding diagrams and descriptions, it seems wrong to be a [control plane node](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/).
According to the overview's [document](https://kubernetes.io/docs/concepts/overview/components/), k8s's clusters is divided into control planes and nodes within clusters, but this is not true.
2. A document on the same page in the diagram describes a worker node, but Looking at the diagram, I don't know what a worker node is.

So, the components
cluster
node
control plane node / worker node
I think to divide it like this.

**Comment by 911432** [comment] 2024-02-21 00:37
1. Due to the corresponding diagrams and descriptions, it seems wrong to be a [control plane node](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/).
According to the overview's [document](https://kubernetes.io/docs/concepts/overview/components/), k8s's clusters is divided into control planes and nodes, but this is not true.
2. A document on the same page in the diagram describes a worker node, but Looking at the diagram, I don't know what a worker node is.

So, the components
cluster
node
control plane node / worker node
I think to divide it like this.

**Comment by 911432** [comment] 2024-02-21 00:37
1. Due to the corresponding diagrams and descriptions, it seems wrong to be a [control plane node](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/).
According to the overview's [document](https://kubernetes.io/docs/concepts/overview/components/), k8s's cluster is divided into control planes and nodes, but this is not true.
2. A document on the same page in the diagram describes a worker node, but Looking at the diagram, I don't know what a worker node is.

So, the components
cluster
node
control plane node / worker node
I think to divide it like this.

**Comment by sftim** [comment] 2024-02-21 09:11
> So, the components
> cluster
> node
> control plane node / worker node
> I think to divide it like this.

Thanks for the suggestion, but I don't think it'll help people learn the true story here.

**Comment by sftim** [comment] 2024-02-21 09:13
/triage unresolved

I'm going to call it: this issue isn't going to help us improve the website.

**Comment by 911432** [comment] 2024-02-21 10:09
Then I'll change it like this.
A cluster is a set of nodes, and nodes are divided into control plane nodes and worker nodes.

**Comment by sftim** [comment] 2024-02-21 13:06
> Then I'll change it for you like this.
> A cluster is a set of nodes, and nodes are divided into control planes and workloads.
> The node acting as the control plane is the control plane node, and the node acting as the workload is the worker node.

Because that set statements isn't generally true, we can't really move forward.

If you make notes now about what is hard to learn, and in the future you feel you've learned the true story here, we'd love the feedback. Right now, I (still) don't think this issue provides actionable feedback.

**Comment by 911432** [comment] 2024-02-21 15:49
- Because that set statements isn't generally true, we can't really move forward.

Does that mean you can create a control plane without a node?
If this statement is true, there should be no [control plane node or etcd node](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/).

The control plane is an uncountable abstract noun, and nodes are felt to be real nouns that can be counted.
It is strange that these two are components of the cluster.
Components can only be understood if they consist only of uncountable abstract nouns or real nouns that can be counted.

**Comment by sftim** [comment] 2024-02-27 16:47
> Does that mean you can create a control plane without a node?

You can create a control plane without having any nodes. However, not if you use pure `kubeadm`, so https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/ is not wrong.

Improvements are welcome, but: this issue isn't helping us understand where to make them. Perhaps you'd be willing to file a new issue that lists the aspects of Kubernetes architecture that you found / are finding confusing @911432? If you do that, and let other contributors propose a way to fix this, I think that will help more.

**Comment by 911432** [comment] 2024-02-28 10:23
Kubernetes's nodes have two definitions.
There are [nodes](https://kubernetes.io/docs/concepts/architecture/nodes/) that mean virtual machines or physical machines,

There are [nodes](https://kubernetes.io/docs/concepts/overview/components/) with kubelet, kube-proxy, and container runtime.

I wanted to classify it by the first meaning node, and @sftim is the second meaning node, explaining that there is a control plane without a node. As a result, we explain that a single control plane can be created without nodes defined by the second meaning.

If I make multiple virtual machines or physical machines with only control plane function, can I call them control plane nodes or control planes? I know I can't.
- You can create a control plane without having any nodes. 
이 뜻은 여러개를 만들 수 있는 것으로 이해된다.

**Comment by 911432** [comment] 2024-02-28 10:25
Kubernetes's nodes have two definitions.
There are [nodes](https://kubernetes.io/docs/concepts/architecture/nodes/) that mean virtual machines or physical machines,

There are [nodes](https://kubernetes.io/docs/concepts/overview/components/) with kubelet, kube-proxy, and container runtime.

I wanted to classify it by the first meaning node, and @sftim is the second meaning node, explaining that there is a control plane without a node. As a result, we explain that a single control plane can be created without nodes defined by the second meaning.

If I make multiple virtual machines or physical machines with only control plane function, can I call them control plane nodes or control planes? I know I can't.
- You can create a control plane without having any nodes. 
It is understood that this meaning can be made into a majority.

**Comment by 911432** [comment] 2024-02-28 10:26
Kubernetes's nodes have two definitions.
There are [nodes](https://kubernetes.io/docs/concepts/architecture/nodes/) that mean virtual machines or physical machines,

There are [nodes](https://kubernetes.io/docs/concepts/overview/components/) with kubelet, kube-proxy, and container runtime.

I wanted to classify it by the first meaning node, and @sftim is the second meaning node, explaining that there is a control plane without a node. As a result, we explain that a single control plane can be created without nodes defined by the second meaning.

If I make multiple virtual machines or physical machines with only control plane function, can I call them control plane nodes or control planes? I know I can't.
- You can create a control plane without having any nodes. 

It is understood that this meaning can be made into a majority.

**Comment by 911432** [comment] 2024-02-28 10:27
Kubernetes's nodes have two definitions.
There are [nodes](https://kubernetes.io/docs/concepts/architecture/nodes/) that mean virtual machines or physical machines,

There are [nodes](https://kubernetes.io/docs/concepts/overview/components/) with kubelet, kube-proxy, and container runtime.

I wanted to classify it by the first meaning node, and @sftim is the second meaning node, explaining that there is a control plane without a node. As a result, we explain that a single control plane can be created without nodes defined by the second meaning.

If I make multiple virtual machines or physical machines with only control plane function, can I call them control plane nodes or control planes? I know I can't.
- You can create a control plane without having any nodes. 

It's understood that you can make these meanings into several things.

**Comment by 911432** [comment] 2024-02-28 10:29
Kubernetes's nodes have two definitions.
There are [nodes](https://kubernetes.io/docs/concepts/architecture/nodes/) that mean virtual machines or physical machines,

There are [nodes](https://kubernetes.io/docs/concepts/overview/components/) with kubelet, kube-proxy, and container runtime.

I wanted to classify it by the first meaning node.
But @sftim is the second meaning node, explaining that there is a control plane without a node. As a result, we explain that a single control plane can be created without nodes defined by the second meaning.

If I make multiple virtual machines or physical machines with only control plane function, can I call them control plane nodes or control planes? I know I can't.
- You can create a control plane without having any nodes. 

It's understood that you can make these meanings into several things.

**Comment by 911432** [comment] 2024-02-28 10:33
Kubernetes's nodes have two definitions.
There are [nodes](https://kubernetes.io/docs/concepts/architecture/nodes/) that mean virtual machines or physical machines,

There are [nodes](https://kubernetes.io/docs/concepts/overview/components/) with kubelet, kube-proxy, and container runtime.

I wanted to classify it by the first meaning node.
But @sftim is the second meaning node, explaining that there is a control plane without a node. As a result, we explain that a single control plane can be created without nodes defined by the second meaning.

If I make multiple virtual machines or physical machines with only control plane function, can I call them control plane nodes or control planes? I know I can't. Because the control plane is an uncountable noun.
- You can create a control plane without having any nodes. 

But It's understood that you can make these meanings into several things.

**Comment by 911432** [comment] 2024-02-28 10:33
Kubernetes's nodes have two definitions.
First, There are [nodes](https://kubernetes.io/docs/concepts/architecture/nodes/) that mean virtual machines or physical machines,

Second, There are [nodes](https://kubernetes.io/docs/concepts/overview/components/) with kubelet, kube-proxy, and container runtime.

I wanted to classify it by the first meaning node.
But @sftim is the second meaning node, explaining that there is a control plane without a node. As a result, we explain that a single control plane can be created without nodes defined by the second meaning.

If I make multiple virtual machines or physical machines with only control plane function, can I call them control plane nodes or control planes? I know I can't. Because the control plane is an uncountable noun.
- You can create a control plane without having any nodes. 

But It's understood that you can make these meanings into several things.

**Comment by sftim** [comment] 2024-02-28 10:36
> First, There are [nodes](https://kubernetes.io/docs/concepts/architecture/nodes/) that mean virtual machines or physical machines,
> 
> Second, There are [nodes](https://kubernetes.io/docs/concepts/overview/components/) with kubelet, kube-proxy, and container runtime.
> 
> I wanted to classify it by the first meaning node.
> But @sftim is the second meaning node, explaining that there is a control plane without a node. As a result, we explain that a single control plane can be created without nodes defined by the second meaning.

I don't think you've understood that right; I also don't think this issue is the right place for helping with that learning.

**Comment by 911432** [comment] 2024-02-28 10:38
Kubernetes's nodes have two definitions.
First, There are [nodes](https://kubernetes.io/docs/concepts/architecture/nodes/) that mean virtual machines or physical machines,

Second, There are [nodes](https://kubernetes.io/docs/concepts/overview/components/) with kubelet, kube-proxy, and container runtime.

I wanted to classify it by the first meaning node.
But @sftim is the second meaning node, explaining that there is a control plane without a node. As a result, we explain that a single control plane can be created without nodes defined by the second meaning.

If I make multiple virtual machines or physical machines with only control plane function, can I call them control plane nodes or control planes? I know I can't. Because the control plane is an uncountable noun.
- You can create a control plane without having any nodes. 

But It's understood that you can make these meanings into several things.
So, I would like to divide it into control plane and workload as the role of node, which is the first meaning.

**Comment by stmcginnis** [comment] 2024-02-28 14:46
> First, There are [nodes](https://kubernetes.io/docs/concepts/architecture/nodes/) that mean virtual machines or physical machines,

> Second, There are [nodes](https://kubernetes.io/docs/concepts/overview/components/) with kubelet, kube-proxy, and container runtime.

These are not two different definitions. They are just two aspects describing the properties of a node.

> can I call them control plane nodes or control planes? I know I can't. 

Again, you are mixing two different concepts. There is only ever one control plane. The underlying infrastructure providing that control plane may be made up of one or more nodes. Or no nodes at all. As a _convention_, if cluster nodes are where those control plane services are running, they are typically called control plane nodes. But they are still just virtual machines or physical machines, running kubelet, kube-proxy, and a container runtime.

So as far as the diagram in question goes, it is very accurate. A Kubernetes cluster has a control plane made up of the api service, etcd, a scheduler, etc. And there are nodes running kubelet. That's the high level concept. If you start to add in the different permutations of how this can be implemented, you either have a diagram that is not always accurate, and busy with too much detail that can make it more confusing - or you need to have several of these diagrams showing all the different ways that the basic concepts that it is currently showing can be implemented.

I'm not saying the diagram couldn't be improved somehow, but it is accurate and simple enough to show just the basic concepts that the page is trying to convey.

**Comment by 911432** [comment] 2024-02-28 22:57
>  That's the high level concept.

Concepts and substance are confused in a single picture.
I can only understand a picture if it is a concept and a concept or an substance and substance.

I mentioned the above problem as below above.

> The control plane is an uncountable abstract noun, and nodes are felt to be real nouns that can be counted.
> It is strange that these two are components of the cluster.
> Components can only be understood if they consist only of uncountable abstract nouns or real nouns that can be counted.

**Comment by stmcginnis** [comment] 2024-02-28 23:00
Control plane count: 1
Node count: 1 or more

It's definitely countable. ;)

**Comment by sftim** [comment] 2024-02-29 10:00
Based on the discussion so far, I propose to close this issue.

**Comment by 911432** [comment] 2024-02-29 11:01
> So as far as the diagram in question goes, it is very accurate. 

@stmcginnis said that the current picture is correct,but it is not correct because it can be a control plane node.

**Comment by sftim** [comment] 2024-02-29 11:09
No fixes identified.
/close

**Closed** 2024-02-29 11:09 UTC
Labels: kind/feature, priority/awaiting-more-evidence, triage/unresolved, language/en, needs-triage

**Comment by stmcginnis** [comment] 2024-02-29 13:02
> There are multiple virtual machines or physical machines that function as control planes,

Nope, here is the mix up in concepts again. There is only ever one control plane. Multiple nodes may, or may not, be used to host that control plane. Since the idea of the control is more important than one of the many ways that control plane can be provided, it is just shown as the one high level concept in the diagram.

**Comment by 911432** [comment] 2024-03-01 02:37
> it's strange that only one control plane is possible and the number of nodes can be counted.

I know that the control plane is concept in the next sentence. And It is true that there are multiple virtual or physical systems that function as control plane.

As @stmcginnis says, concepts (control planes) manage objects (nodes).
In other words, it is the drawings and documents of k8s that describe the mixture of the two meanings.
This is confusing if something like a worker node or a control plane node later appears.

I want pictures and documents to be explained by concepts and concepts or by the relationship between objects and objects.
