### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

### ISSUE THREAD

**Issue by albertchan** [kubernetes/website#8594] opened 2018-05-17 16:09 UTC
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

Link to the GitHub repository returns 404.

**Proposed Solution:**

Update link to appropriate location in repo.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

**Comment by ajaeger** [comment] 2018-05-18 05:25
/triage duplicate

Duplicate of #8547

**Comment by shubheksha** [comment] 2018-09-22 16:01
Closing this as it's a duplicate.
/close

**Closed by shubheksha** 2018-09-22 16:01 UTC
Labels: lifecycle/rotten, triage/duplicate
