### ISSUE TITLE
Using kubectl to Create a Deployment

### ISSUE THREAD

**Issue by wradstok** [kubernetes/website#44756] opened 2024-01-15 14:42 UTC
I'm following the `Learn Kubernetes Basic` tutorials and have reached the `Deploy an app` step. However, when I run the suggested command:

`kubectl create deployment kubernetes-bootcamp --image=gcr.io/google-samples/kubernetes-bootcamp:v1`

the deployment "works" , but the pod never becomes ready:

```
❯  kubectl get deployments
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
kubernetes-bootcamp   0/1     1            0           67m
```

Attempting to get the logs results in error:
```
❯ kubectl logs kubernetes-bootcamp-f95c5b745-fwjdm
exec /bin/sh: exec format error
````

Browsing the internet this error seems to suggest that I am running a container for the wrong platform. Indeed I am on a M2 macbook, so this makes sense. Is there another container I can use to finish the tutorial built for arm64?

**Comment by Gauravpadam** [comment] 2024-01-15 15:01
Hey @wradstok, I'm not able to reproduce your problem
Here's what I suggest to troubleshoot, try creating a minikube cluster in a cloud environment (something like codespaces)
and try the deployment on it. This will rule out your system and shorten the scope of the error

If you need further assistance, support tickets are not the correct platform. I suggest asking in [Kubernetes Slack](https://slack.k8s.io)

/kind support
/triage not-reproducible

**Comment by adityasamant25** [comment] 2024-01-16 03:39
Hi @wradstok,
It is correct that the image used within this page does not work on an arm64 architecture.
You can try what @Gauravpadam suggested.
Another way to make this work on a Macbook with the silicon chip (M-series) is to use Minikube with the docker desktop as a driver. Docker desktop has the ability to emulate AMD64, and the tutorial will pass.

PR #44279 is raised to add a note to this page to highlight this point. The PR is currently awaiting and approval and merge.

**Comment by adityasamant25** [comment] 2024-01-16 03:41
Duplicate of #44271

triage/duplicate

**Comment by sftim** [comment] 2024-01-16 10:46
/remove-kind support

Unless the page tells you the clue (that only AMD64 is supported), then we can't / shouldn't expect readers to know that.
However, this _is_ a duplicate bug report.

**Comment by azn-abel** [comment] 2024-01-17 18:17
/remove-triage not-reproducible
/triage duplicate 
/kind bug

Duplicate of #44271 as mentioned above, kind bug as mentioned above

**Comment by adityasamant25** [comment] 2024-01-22 12:24
#44271 is closed.
So this issue can be closed as well.

**Closed** 2024-01-24 07:24 UTC
Labels: kind/bug, triage/duplicate, needs-kind, needs-triage
