### ISSUE TITLE
Issue with k8s.io/docs/admin/high-availability/building/

### ISSUE THREAD

**Issue by xornet-sl** [kubernetes/website#9033] opened 2018-06-11 23:28 UTC
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Invalid yaml-files URLs in document https://kubernetes.io/docs/admin/high-availability/building/
There are some yaml examples on this page. All of them don't work.
For example:
https://kubernetes.io/docs/admin/high-availability/etcd.yaml
https://kubernetes.io/docs/admin/high-availability/kube-apiserver.yaml
https://kubernetes.io/docs/admin/high-availability/kube-scheduler.yaml
https://kubernetes.io/docs/admin/high-availability/kube-controller-manager.yaml

**Page to Update:**
https://kubernetes.io/docs/admin/high-availability/building/

**Comment by neolit123** [comment] 2018-06-11 23:31
duplicate of:
https://github.com/kubernetes/website/issues/8485

/close

**Closed by neolit123** 2018-06-11 23:31 UTC
